# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasuplier',
            fields=[
                ('kode_suplier', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_suplier', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('rekening', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'datasuplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industrifarmasi',
            fields=[
                ('kode_industri', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_industri', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'industrifarmasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisProdusen',
            fields=[
                ('kode_produsen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_produsen', models.CharField(blank=True, max_length=40, null=True)),
                ('alamat_produsen', models.CharField(blank=True, max_length=70, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('website_produsen', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'inventaris_produsen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisSuplier',
            fields=[
                ('kode_suplier', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_suplier', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('rekening', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inventaris_suplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrssuplier',
            fields=[
                ('kode_suplier', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_suplier', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('rekening', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ipsrssuplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pemberihibah',
            fields=[
                ('kode_pemberi', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_pemberi', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'pemberihibah',
                'managed': False,
            },
        ),
    ]
