# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranap', '0001_initial'),
        ('pegawai', '0001_initial'),
        ('keuangan', '0001_initial'),
        ('ralan', '0001_initial'),
        ('bangsal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailNotaJalan',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('besarppn', models.FloatField(blank=True, null=True)),
                ('besar_bayar', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_nota_jalan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailpiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
                ('aturan_pakai', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'detailpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPiutangPasien',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('totalpiutang', models.FloatField(blank=True, null=True)),
                ('sisapiutang', models.FloatField(blank=True, null=True)),
                ('tgltempo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_piutang_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detreturpiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_piutang', models.CharField(max_length=20)),
                ('jml_piutang', models.FloatField(blank=True, null=True)),
                ('h_piutang', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detreturpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriPemasukanLain',
            fields=[
                ('kode_kategori', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'kategori_pemasukan_lain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriPengeluaranHarian',
            fields=[
                ('kode_kategori', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'kategori_pengeluaran_harian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTunjanganBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=60)),
                ('tnj', models.FloatField()),
            ],
            options={
                'db_table': 'master_tunjangan_bulanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTunjanganHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('tnj', models.FloatField()),
            ],
            options={
                'db_table': 'master_tunjangan_harian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatrikAkunJnsPerawatan',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.jnsperawatan')),
            ],
            options={
                'db_table': 'matrik_akun_jns_perawatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatrikAkunJnsPerawatanInap',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ranap.jnsperawataninap')),
            ],
            options={
                'db_table': 'matrik_akun_jns_perawatan_inap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaInap',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('no_nota', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('uang_muka', models.FloatField(blank=True, db_column='Uang_Muka', null=True)),
            ],
            options={
                'db_table': 'nota_inap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaJalan',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('no_nota', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nota_jalan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PemasukanLain',
            fields=[
                ('no_masuk', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField()),
                ('besar', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('keperluan', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'pemasukan_lain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenagihanPiutang',
            fields=[
                ('no_tagihan', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('tanggaltempo', models.DateField()),
                ('tempo', models.IntegerField()),
                ('catatan', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'penagihan_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengeluaranHarian',
            fields=[
                ('no_keluar', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField()),
                ('biaya', models.FloatField()),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pengeluaran_harian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengembalianDeposit',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateTimeField()),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('besar_pengembalian', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pengembalian_deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenguranganBiaya',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('nama_pengurangan', models.CharField(max_length=60)),
                ('besar_pengurangan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pengurangan_biaya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piutang',
            fields=[
                ('nota_piutang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_piutang', models.DateField(blank=True, null=True)),
                ('nm_pasien', models.CharField(blank=True, max_length=50, null=True)),
                ('catatan', models.CharField(blank=True, max_length=40, null=True)),
                ('jns_jual', models.CharField(blank=True, max_length=11, null=True)),
                ('ongkir', models.FloatField(blank=True, null=True)),
                ('uangmuka', models.FloatField(blank=True, null=True)),
                ('sisapiutang', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('tgltempo', models.DateField()),
            ],
            options={
                'db_table': 'piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PiutangPasien',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_piutang', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=11)),
                ('totalpiutang', models.FloatField(blank=True, null=True)),
                ('uangmuka', models.FloatField(blank=True, null=True)),
                ('sisapiutang', models.FloatField()),
                ('tgltempo', models.DateField()),
            ],
            options={
                'db_table': 'piutang_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PnmTnjBulanan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'pnm_tnj_bulanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PnmTnjHarian',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'pnm_tnj_harian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('kd_rek', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_rek', models.CharField(blank=True, max_length=100, null=True)),
                ('tipe', models.CharField(blank=True, max_length=1, null=True)),
                ('balance', models.CharField(blank=True, max_length=1, null=True)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'rekening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rekeningtahun',
            fields=[
                ('thn', models.TextField(primary_key=True, serialize=False)),
                ('saldo_awal', models.FloatField()),
            ],
            options={
                'db_table': 'rekeningtahun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returpiutang',
            fields=[
                ('no_retur_piutang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'returpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatNaikGaji',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('pangkatjabatan', models.CharField(max_length=50)),
                ('gapok', models.FloatField()),
                ('tmt_berkala', models.DateField()),
                ('tmt_berkala_yad', models.DateField()),
                ('no_sk', models.CharField(max_length=25)),
                ('tgl_sk', models.DateField()),
                ('masa_kerja', models.IntegerField()),
                ('bulan_kerja', models.IntegerField()),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'riwayat_naik_gaji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'set_akun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkunRalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'set_akun_ralan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkunRanap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'set_akun_ranap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkunRanap2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'set_akun_ranap2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHargaKamar',
            fields=[
                ('kd_kamar', models.OneToOneField(db_column='kd_kamar', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bangsal.kamar')),
                ('tarif', models.FloatField()),
            ],
            options={
                'db_table': 'set_harga_kamar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetModalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_awal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set_modal_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaralan', models.CharField(max_length=11)),
                ('kwitansiralan', models.CharField(max_length=11)),
                ('nota1ranap', models.CharField(max_length=11)),
                ('nota2ranap', models.CharField(max_length=11)),
                ('kwitansiranap', models.CharField(max_length=11)),
                ('notaapotek', models.CharField(max_length=11)),
                ('notalabrad', models.CharField(max_length=11)),
                ('notatoko', models.CharField(max_length=11)),
                ('cetaknotasimpanralan', models.CharField(max_length=3)),
                ('cetaknotasimpanranap', models.CharField(max_length=3)),
                ('rinciandokterralan', models.CharField(max_length=3)),
                ('rinciandokterranap', models.CharField(max_length=3)),
                ('centangdokterralan', models.CharField(max_length=3)),
                ('centangdokterranap', models.CharField(max_length=3)),
                ('tampilkan_administrasi_di_billingranap', models.CharField(max_length=3)),
                ('rincianoperasi', models.CharField(blank=True, max_length=3, null=True)),
                ('tampilkan_ppnobat_ralan', models.CharField(blank=True, max_length=3, null=True)),
                ('tampilkan_ppnobat_ranap', models.CharField(blank=True, max_length=3, null=True)),
                ('tampilkan_tombol_nota_ralan', models.CharField(blank=True, max_length=3, null=True)),
                ('tampilkan_tombol_nota_ranap', models.CharField(blank=True, max_length=3, null=True)),
                ('verifikasi_penjualan_di_kasir', models.CharField(blank=True, max_length=3, null=True)),
                ('verifikasi_penyerahan_darah_di_kasir', models.CharField(blank=True, max_length=3, null=True)),
                ('cetaknotasimpanpenjualan', models.CharField(blank=True, max_length=3, null=True)),
                ('tampilkan_tombol_nota_penjualan', models.CharField(blank=True, max_length=3, null=True)),
                ('centangobatralan', models.CharField(blank=True, max_length=3, null=True)),
                ('centangobatranap', models.CharField(blank=True, max_length=3, null=True)),
                ('cetaknotasimpantoko', models.CharField(max_length=3)),
                ('tampilkan_tombol_nota_toko', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'set_nota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poli_ralan', models.CharField(max_length=3)),
                ('cara_bayar_ralan', models.CharField(max_length=3)),
                ('ruang_ranap', models.CharField(max_length=3)),
                ('cara_bayar_ranap', models.CharField(max_length=3)),
                ('cara_bayar_lab', models.CharField(max_length=3)),
                ('cara_bayar_radiologi', models.CharField(max_length=3)),
                ('cara_bayar_operasi', models.CharField(blank=True, max_length=3, null=True)),
                ('kelas_ranap', models.CharField(max_length=3)),
                ('kelas_lab', models.CharField(max_length=3)),
                ('kelas_radiologi', models.CharField(max_length=3)),
                ('kelas_operasi', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'set_tarif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetTarifOnline',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.jnsperawatan')),
            ],
            options={
                'db_table': 'set_tarif_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagihanBpdJateng',
            fields=[
                ('nm_pasien', models.CharField(blank=True, max_length=40, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tgl_lahir', models.DateField()),
                ('umurdaftar', models.CharField(blank=True, max_length=7, null=True)),
                ('tgl_registrasi', models.DateField(blank=True, null=True)),
                ('no_nota', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('besar_bayar', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('no_rawat', models.CharField(blank=True, max_length=17, null=True)),
                ('status_lanjut', models.CharField(blank=True, max_length=13, null=True)),
                ('tgl_closing', models.DateField(blank=True, null=True)),
                ('status_bayar', models.CharField(blank=True, max_length=7, null=True)),
                ('kasir', models.CharField(blank=True, max_length=50, null=True)),
                ('diupdatebank', models.DateTimeField(blank=True, null=True)),
                ('referensi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tagihan_bpd_jateng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagihanSadewa',
            fields=[
                ('no_nota', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('no_rkm_medis', models.CharField(max_length=15)),
                ('nama_pasien', models.CharField(max_length=60)),
                ('alamat', models.CharField(max_length=200)),
                ('tgl_bayar', models.DateTimeField()),
                ('jenis_bayar', models.CharField(max_length=9)),
                ('jumlah_tagihan', models.FloatField()),
                ('jumlah_bayar', models.FloatField()),
                ('status', models.CharField(max_length=5)),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tagihan_sadewa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TambahanBiaya',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('nama_biaya', models.CharField(max_length=60)),
                ('besar_biaya', models.FloatField()),
            ],
            options={
                'db_table': 'tambahan_biaya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AkunPenagihanPiutang',
            fields=[
                ('kd_rek', models.OneToOneField(db_column='kd_rek', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keuangan.rekening')),
                ('nama_bank', models.CharField(blank=True, max_length=70, null=True)),
                ('atas_nama', models.CharField(blank=True, max_length=50, null=True)),
                ('no_rek', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'akun_penagihan_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuktiPenagihanPiutang',
            fields=[
                ('no_tagihan', models.OneToOneField(db_column='no_tagihan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keuangan.penagihanpiutang')),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bukti_penagihan_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPenagihanPiutang',
            fields=[
                ('no_tagihan', models.OneToOneField(db_column='no_tagihan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keuangan.penagihanpiutang')),
                ('sisapiutang', models.FloatField()),
            ],
            options={
                'db_table': 'detail_penagihan_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkunBankbri',
            fields=[
                ('kd_rek', models.OneToOneField(db_column='kd_rek', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keuangan.rekening')),
                ('consumer_key', models.CharField(blank=True, max_length=700, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=700, null=True)),
                ('institution_code', models.CharField(blank=True, max_length=700, null=True)),
                ('briva_no', models.CharField(blank=True, max_length=700, null=True)),
                ('urlapi', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'set_akun_bankbri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAkunBankjateng',
            fields=[
                ('kd_rek', models.OneToOneField(db_column='kd_rek', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keuangan.rekening')),
                ('usere', models.CharField(blank=True, max_length=700, null=True)),
                ('passworde', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'set_akun_bankjateng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subrekening',
            fields=[
                ('kd_rek2', models.OneToOneField(db_column='kd_rek2', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='kd_rek2_subrekening', serialize=False, to='keuangan.rekening')),
            ],
            options={
                'db_table': 'subrekening',
                'managed': False,
            },
        ),
    ]
