# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkir',
            fields=[
                ('nomer_kartu', models.CharField(blank=True, max_length=5, null=True)),
                ('no_kendaraan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_masuk', models.DateField()),
                ('jam_masuk', models.TimeField()),
                ('tgl_keluar', models.DateField(blank=True, null=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('lama_parkir', models.IntegerField(blank=True, null=True)),
                ('ttl_biaya', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parkir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkirBarcode',
            fields=[
                ('kode_barcode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nomer_kartu', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'parkir_barcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkirJenis',
            fields=[
                ('kd_parkir', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jns_parkir', models.CharField(max_length=50)),
                ('biaya', models.FloatField()),
                ('jenis', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'parkir_jenis',
                'managed': False,
            },
        ),
    ]
