# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ralan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTriaseIgd',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_kunjungan', models.DateTimeField()),
                ('cara_masuk', models.CharField(max_length=10)),
                ('alat_transportasi', models.CharField(max_length=7)),
                ('alasan_kedatangan', models.CharField(max_length=14)),
                ('keterangan_kedatangan', models.CharField(max_length=100)),
                ('tekanan_darah', models.CharField(max_length=8)),
                ('nadi', models.CharField(max_length=3)),
                ('pernapasan', models.CharField(max_length=3)),
                ('suhu', models.CharField(max_length=5)),
                ('saturasi_o2', models.CharField(max_length=3)),
                ('nyeri', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'data_triase_igd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgddetailSkala1',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'data_triase_igddetail_skala1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgddetailSkala2',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'data_triase_igddetail_skala2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgddetailSkala3',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'data_triase_igddetail_skala3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgddetailSkala4',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'data_triase_igddetail_skala4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgddetailSkala5',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'data_triase_igddetail_skala5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgdprimer',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('keluhan_utama', models.CharField(max_length=400)),
                ('kebutuhan_khusus', models.CharField(max_length=12)),
                ('catatan', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=16)),
                ('tanggaltriase', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_triase_igdprimer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTriaseIgdsekunder',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('anamnesa_singkat', models.CharField(max_length=400)),
                ('catatan', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=11)),
                ('tanggaltriase', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_triase_igdsekunder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyIndex',
            fields=[
                ('kode_emergency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_emergency', models.CharField(blank=True, max_length=200, null=True)),
                ('indek', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergency_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseMacamKasus',
            fields=[
                ('kode_kasus', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('macam_kasus', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_macam_kasus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriasePemeriksaan',
            fields=[
                ('kode_pemeriksaan', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_pemeriksaan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'master_triase_pemeriksaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseSkala1',
            fields=[
                ('kode_skala1', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengkajian_skala1', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_skala1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseSkala2',
            fields=[
                ('kode_skala2', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengkajian_skala2', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_skala2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseSkala3',
            fields=[
                ('kode_skala3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengkajian_skala3', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_skala3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseSkala4',
            fields=[
                ('kode_skala4', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengkajian_skala4', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_skala4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTriaseSkala5',
            fields=[
                ('kode_skala5', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengkajian_skala5', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_triase_skala5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenilaianAwalKeperawatanIgd',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateTimeField()),
                ('informasi', models.CharField(max_length=13)),
                ('keluhan_utama', models.TextField()),
                ('rpd', models.TextField()),
                ('rpo', models.TextField()),
                ('status_kehamilan', models.CharField(max_length=11)),
                ('gravida', models.CharField(blank=True, max_length=20, null=True)),
                ('para', models.CharField(blank=True, max_length=20, null=True)),
                ('abortus', models.CharField(blank=True, max_length=20, null=True)),
                ('hpht', models.CharField(blank=True, max_length=20, null=True)),
                ('tekanan', models.CharField(max_length=12)),
                ('pupil', models.CharField(max_length=8)),
                ('neurosensorik', models.CharField(max_length=28)),
                ('integumen', models.CharField(max_length=14)),
                ('turgor', models.CharField(max_length=7)),
                ('edema', models.CharField(max_length=13)),
                ('mukosa', models.CharField(max_length=6)),
                ('perdarahan', models.CharField(max_length=9)),
                ('jumlah_perdarahan', models.CharField(blank=True, max_length=5, null=True)),
                ('warna_perdarahan', models.CharField(blank=True, max_length=40, null=True)),
                ('intoksikasi', models.CharField(max_length=16)),
                ('bab', models.CharField(blank=True, max_length=2, null=True)),
                ('xbab', models.CharField(blank=True, max_length=10, null=True)),
                ('kbab', models.CharField(blank=True, max_length=40, null=True)),
                ('wbab', models.CharField(blank=True, max_length=40, null=True)),
                ('bak', models.CharField(blank=True, max_length=2, null=True)),
                ('xbak', models.CharField(blank=True, max_length=10, null=True)),
                ('wbak', models.CharField(blank=True, max_length=40, null=True)),
                ('lbak', models.CharField(blank=True, max_length=40, null=True)),
                ('psikologis', models.CharField(max_length=17)),
                ('jiwa', models.CharField(max_length=5)),
                ('perilaku', models.CharField(max_length=34)),
                ('dilaporkan', models.CharField(blank=True, max_length=50, null=True)),
                ('sebutkan', models.CharField(blank=True, max_length=50, null=True)),
                ('hubungan', models.CharField(max_length=15)),
                ('tinggal_dengan', models.CharField(max_length=13)),
                ('ket_tinggal', models.CharField(blank=True, max_length=50, null=True)),
                ('budaya', models.CharField(max_length=9)),
                ('ket_budaya', models.CharField(max_length=50)),
                ('pendidikan_pj', models.CharField(max_length=14)),
                ('ket_pendidikan_pj', models.CharField(blank=True, max_length=50, null=True)),
                ('edukasi', models.CharField(max_length=8)),
                ('ket_edukasi', models.CharField(max_length=50)),
                ('kemampuan', models.CharField(max_length=20)),
                ('aktifitas', models.CharField(max_length=12)),
                ('alat_bantu', models.CharField(max_length=5)),
                ('ket_bantu', models.CharField(blank=True, max_length=50, null=True)),
                ('nyeri', models.CharField(max_length=15)),
                ('provokes', models.CharField(max_length=15)),
                ('ket_provokes', models.CharField(max_length=40)),
                ('quality', models.CharField(max_length=16)),
                ('ket_quality', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=50)),
                ('menyebar', models.CharField(max_length=5)),
                ('skala_nyeri', models.CharField(max_length=2)),
                ('durasi', models.CharField(max_length=25)),
                ('nyeri_hilang', models.CharField(max_length=14)),
                ('ket_nyeri', models.CharField(blank=True, max_length=40, null=True)),
                ('pada_dokter', models.CharField(max_length=5)),
                ('ket_dokter', models.CharField(blank=True, max_length=15, null=True)),
                ('berjalan_a', models.CharField(max_length=5)),
                ('berjalan_b', models.CharField(max_length=5)),
                ('berjalan_c', models.CharField(max_length=5)),
                ('hasil', models.CharField(max_length=40)),
                ('lapor', models.CharField(max_length=5)),
                ('ket_lapor', models.CharField(blank=True, max_length=15, null=True)),
                ('rencana', models.TextField()),
            ],
            options={
                'db_table': 'penilaian_awal_keperawatan_igd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenilaianAwalKeperawatanIgdMasalah',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'penilaian_awal_keperawatan_igd_masalah',
                'managed': False,
            },
        ),
    ]
