# Generated by Django 4.1 on 2022-11-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_bidang', to='auth_bangsal.departement')),
            ],
            options={
                'db_table': 'bidang',
            },
        ),
        migrations.CreateModel(
            name='Bangsal',
            fields=[
                ('kd_bangsal', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidang_bangsal', to='auth_bangsal.bidang')),
            ],
            options={
                'db_table': 'bangsal',
            },
        ),
    ]
