# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usere', models.TextField(blank=True, null=True)),
                ('passworde', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Runtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('aktifkan', models.CharField(max_length=3)),
                ('gambar', models.TextField()),
            ],
            options={
                'db_table': 'runtext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Runtextapotek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('aktifkan', models.CharField(max_length=3)),
                ('gambar', models.TextField()),
            ],
            options={
                'db_table': 'runtextapotek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setsms',
            fields=[
                ('kode_sms', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sintax_balasan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'setsms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('nama_instansi', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('alamat_instansi', models.CharField(blank=True, max_length=150, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=30, null=True)),
                ('propinsi', models.CharField(blank=True, max_length=30, null=True)),
                ('kontak', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('aktifkan', models.CharField(max_length=3)),
                ('kode_ppk', models.CharField(blank=True, max_length=15, null=True)),
                ('kode_ppkinhealth', models.CharField(blank=True, max_length=15, null=True)),
                ('kode_ppkkemenkes', models.CharField(blank=True, max_length=15, null=True)),
                ('wallpaper', models.TextField(blank=True, null=True)),
                ('logo', models.TextField()),
            ],
            options={
                'db_table': 'setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id_pesan', models.AutoField(primary_key=True, serialize=False)),
                ('sms_masuk', models.CharField(blank=True, max_length=255, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('pdu_pesan', models.CharField(blank=True, max_length=255, null=True)),
                ('encoding', models.CharField(blank=True, max_length=20, null=True)),
                ('id_gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_sms', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuratBalas',
            fields=[
                ('kd', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('balas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'surat_balas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuratBebasTato',
            fields=[
                ('no_surat', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggalperiksa', models.DateField()),
                ('hasilperiksa', models.CharField(max_length=10)),
                ('keperluan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'surat_bebas_tato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuratBebasTbc',
            fields=[
                ('no_surat', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tanggalsurat', models.DateField(blank=True, null=True)),
                ('keperluan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'surat_bebas_tbc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuratButaWarna',
            fields=[
                ('no_surat', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggalperiksa', models.DateField()),
                ('hasilperiksa', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'surat_buta_warna',
                'managed': False,
            },
        ),
    ]
