# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeslingLimbahB3Medis',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('jmllimbah', models.FloatField(blank=True, null=True)),
                ('tujuan_penyerahan', models.CharField(blank=True, max_length=50, null=True)),
                ('bukti_dokumen', models.CharField(blank=True, max_length=20, null=True)),
                ('sisa_di_tps', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kesling_limbah_b3medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeslingLimbahDomestik',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('jumlahlimbah', models.FloatField(blank=True, null=True)),
                ('tanggalangkut', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kesling_limbah_domestik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeslingMutuAirLimbah',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('meteran', models.FloatField(blank=True, null=True)),
                ('jumlahharian', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('suhu', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kesling_mutu_air_limbah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeslingPemakaianAirPdam',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('meteran', models.FloatField(blank=True, null=True)),
                ('jumlahharian', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kesling_pemakaian_air_pdam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeslingPemakaianAirTanah',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('meteran', models.FloatField(blank=True, null=True)),
                ('jumlahharian', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kesling_pemakaian_air_tanah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeslingPestControl',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.petugas')),
                ('tanggal', models.DateTimeField()),
                ('rincian_kegiatan', models.TextField(blank=True, null=True)),
                ('rekomendasi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kesling_pest_control',
                'managed': False,
            },
        ),
    ]
