# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K3RsBagianTubuh',
            fields=[
                ('kode_bagian', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bagian_tubuh', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_bagian_tubuh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsDampakCidera',
            fields=[
                ('kode_dampak', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dampak_cidera', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_dampak_cidera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsJenisCidera',
            fields=[
                ('kode_cidera', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenis_cidera', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_jenis_cidera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsJenisLuka',
            fields=[
                ('kode_luka', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenis_luka', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_jenis_luka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsJenisPekerjaan',
            fields=[
                ('kode_pekerjaan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenis_pekerjaan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_jenis_pekerjaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsLokasiKejadian',
            fields=[
                ('kode_lokasi', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lokasi_kejadian', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_lokasi_kejadian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsPenyebab',
            fields=[
                ('kode_penyebab', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('penyebab_kecelakaan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'k3rs_penyebab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='K3RsPeristiwa',
            fields=[
                ('no_k3rs', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_insiden', models.DateField()),
                ('waktu_insiden', models.TimeField()),
                ('tgl_pelaporan', models.DateField()),
                ('waktu_pelaporan', models.TimeField()),
                ('kronologi_kejadian', models.CharField(max_length=300)),
                ('kategori_cidera', models.CharField(max_length=6)),
                ('lt', models.IntegerField()),
                ('penyebab_langsung_kondisi', models.CharField(max_length=100)),
                ('penyebab_langsung_tindakan', models.CharField(max_length=100)),
                ('penyebab_tidak_langsung_pribadi', models.CharField(max_length=100)),
                ('penyebab_tidak_langsung_pekerjaan', models.CharField(max_length=100)),
                ('barang_bukti', models.CharField(max_length=5)),
                ('perbaikan_jenis_tindakan', models.CharField(max_length=19)),
                ('perbaikan_rencana_tindakan', models.CharField(max_length=200)),
                ('perbaikan_target', models.DateField()),
                ('perbaikan_wewenang', models.CharField(max_length=100)),
                ('catatan', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'k3rs_peristiwa',
                'managed': False,
            },
        ),
    ]
