# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ralan', '0001_initial'),
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPeriksaLab',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('nilai', models.CharField(max_length=60)),
                ('nilai_rujukan', models.CharField(max_length=30)),
                ('keterangan', models.CharField(max_length=60)),
                ('bagian_rs', models.FloatField()),
                ('bhp', models.FloatField()),
                ('bagian_perujuk', models.FloatField()),
                ('bagian_dokter', models.FloatField()),
                ('bagian_laborat', models.FloatField()),
                ('kso', models.FloatField(blank=True, null=True)),
                ('menejemen', models.FloatField(blank=True, null=True)),
                ('biaya_item', models.FloatField()),
            ],
            options={
                'db_table': 'detail_periksa_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPeriksaLabpa',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('diagnosa_klinik', models.CharField(blank=True, max_length=50, null=True)),
                ('makroskopik', models.CharField(blank=True, max_length=1024, null=True)),
                ('mikroskopik', models.CharField(blank=True, max_length=1024, null=True)),
                ('kesimpulan', models.CharField(blank=True, max_length=300, null=True)),
                ('kesan', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'detail_periksa_labpa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPeriksaLabpaGambar',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'detail_periksa_labpa_gambar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JnsPerawatanLab',
            fields=[
                ('kd_jenis_prw', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_perawatan', models.CharField(blank=True, max_length=80, null=True)),
                ('bagian_rs', models.FloatField(blank=True, null=True)),
                ('bhp', models.FloatField()),
                ('tarif_perujuk', models.FloatField()),
                ('tarif_tindakan_dokter', models.FloatField()),
                ('tarif_tindakan_petugas', models.FloatField(blank=True, null=True)),
                ('kso', models.FloatField(blank=True, null=True)),
                ('menejemen', models.FloatField(blank=True, null=True)),
                ('total_byr', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('kelas', models.CharField(max_length=11)),
                ('kategori', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'jns_perawatan_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriksaLab',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('bagian_rs', models.FloatField()),
                ('bhp', models.FloatField()),
                ('tarif_perujuk', models.FloatField()),
                ('tarif_tindakan_dokter', models.FloatField()),
                ('tarif_tindakan_petugas', models.FloatField()),
                ('kso', models.FloatField(blank=True, null=True)),
                ('menejemen', models.FloatField(blank=True, null=True)),
                ('biaya', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('kategori', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'periksa_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanLab',
            fields=[
                ('noorder', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_permintaan', models.DateField()),
                ('jam_permintaan', models.TimeField()),
                ('tgl_sampel', models.DateField()),
                ('jam_sampel', models.TimeField()),
                ('tgl_hasil', models.DateField()),
                ('jam_hasil', models.TimeField()),
                ('status', models.CharField(max_length=5)),
                ('informasi_tambahan', models.CharField(max_length=60)),
                ('diagnosa_klinis', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'permintaan_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanLabpa',
            fields=[
                ('noorder', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_permintaan', models.DateField()),
                ('jam_permintaan', models.TimeField()),
                ('tgl_sampel', models.DateField()),
                ('jam_sampel', models.TimeField()),
                ('tgl_hasil', models.DateField()),
                ('jam_hasil', models.TimeField()),
                ('status', models.CharField(max_length=5)),
                ('informasi_tambahan', models.CharField(max_length=60)),
                ('diagnosa_klinis', models.CharField(max_length=80)),
                ('pengambilan_bahan', models.DateField(blank=True, null=True)),
                ('diperoleh_dengan', models.CharField(blank=True, max_length=40, null=True)),
                ('lokasi_jaringan', models.CharField(blank=True, max_length=40, null=True)),
                ('diawetkan_dengan', models.CharField(blank=True, max_length=40, null=True)),
                ('pernah_dilakukan_di', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_pa_sebelumnya', models.DateField(blank=True, null=True)),
                ('nomor_pa_sebelumnya', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosa_pa_sebelumnya', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'permintaan_labpa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaranKesanLab',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('saran', models.CharField(blank=True, max_length=700, null=True)),
                ('kesan', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'saran_kesan_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetPjlab',
            fields=[
                ('kd_dokterlab', models.OneToOneField(db_column='kd_dokterlab', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='kd_dokterlab_setpjlab', serialize=False, to='pegawai.dokter')),
            ],
            options={
                'db_table': 'set_pjlab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateLaboratorium',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('pemeriksaan', models.CharField(db_column='Pemeriksaan', max_length=200)),
                ('satuan', models.CharField(max_length=20)),
                ('nilai_rujukan_ld', models.CharField(max_length=30)),
                ('nilai_rujukan_la', models.CharField(max_length=30)),
                ('nilai_rujukan_pd', models.CharField(max_length=30)),
                ('nilai_rujukan_pa', models.CharField(max_length=30)),
                ('bagian_rs', models.FloatField()),
                ('bhp', models.FloatField()),
                ('bagian_perujuk', models.FloatField()),
                ('bagian_dokter', models.FloatField()),
                ('bagian_laborat', models.FloatField()),
                ('kso', models.FloatField(blank=True, null=True)),
                ('menejemen', models.FloatField(blank=True, null=True)),
                ('biaya_item', models.FloatField()),
                ('urut', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_laboratorium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanDetailPermintaanLab',
            fields=[
                ('noorder', models.OneToOneField(db_column='noorder', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='laboratorium.permintaanlab')),
                ('stts_bayar', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'permintaan_detail_permintaan_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanPemeriksaanLab',
            fields=[
                ('noorder', models.OneToOneField(db_column='noorder', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='laboratorium.permintaanlab')),
                ('stts_bayar', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'permintaan_pemeriksaan_lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanPemeriksaanLabpa',
            fields=[
                ('noorder', models.OneToOneField(db_column='noorder', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='laboratorium.permintaanlabpa')),
                ('stts_bayar', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'permintaan_pemeriksaan_labpa',
                'managed': False,
            },
        ),
    ]
