# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antriapotek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loket', models.IntegerField()),
                ('antrian', models.IntegerField()),
            ],
            options={
                'db_table': 'antriapotek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AturanPakai',
            fields=[
                ('tgl_perawatan', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('aturan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'aturan_pakai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeriObatOperasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('hargasatuan', models.FloatField()),
                ('jumlah', models.FloatField()),
            ],
            options={
                'db_table': 'beri_obat_operasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Databarang',
            fields=[
                ('kode_brng', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(blank=True, max_length=80, null=True)),
                ('letak_barang', models.CharField(blank=True, max_length=50, null=True)),
                ('dasar', models.FloatField()),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('ralan', models.FloatField(blank=True, null=True)),
                ('kelas1', models.FloatField(blank=True, null=True)),
                ('kelas2', models.FloatField(blank=True, null=True)),
                ('kelas3', models.FloatField(blank=True, null=True)),
                ('utama', models.FloatField(blank=True, null=True)),
                ('vip', models.FloatField(blank=True, null=True)),
                ('vvip', models.FloatField(blank=True, null=True)),
                ('beliluar', models.FloatField(blank=True, null=True)),
                ('jualbebas', models.FloatField(blank=True, null=True)),
                ('karyawan', models.FloatField(blank=True, null=True)),
                ('stokminimal', models.FloatField(blank=True, null=True)),
                ('isi', models.FloatField()),
                ('kapasitas', models.FloatField()),
                ('expire', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'databarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('no_batch', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_beli', models.DateField()),
                ('tgl_kadaluarsa', models.DateField()),
                ('asal', models.CharField(max_length=10)),
                ('no_faktur', models.CharField(max_length=20)),
                ('dasar', models.FloatField()),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('ralan', models.FloatField(blank=True, null=True)),
                ('kelas1', models.FloatField(blank=True, null=True)),
                ('kelas2', models.FloatField(blank=True, null=True)),
                ('kelas3', models.FloatField(blank=True, null=True)),
                ('utama', models.FloatField(blank=True, null=True)),
                ('vip', models.FloatField(blank=True, null=True)),
                ('vvip', models.FloatField(blank=True, null=True)),
                ('beliluar', models.FloatField(blank=True, null=True)),
                ('jualbebas', models.FloatField(blank=True, null=True)),
                ('karyawan', models.FloatField(blank=True, null=True)),
                ('jumlahbeli', models.FloatField()),
                ('sisa', models.FloatField()),
            ],
            options={
                'db_table': 'data_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailbeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('jumlah2', models.FloatField(blank=True, null=True)),
                ('kadaluarsa', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detailbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailjual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('tambahan', models.FloatField(blank=True, null=True)),
                ('embalase', models.FloatField()),
                ('tuslah', models.FloatField()),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('total', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detailjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailObatRacikan',
            fields=[
                ('tgl_perawatan', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('no_racik', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'detail_obat_racikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPemberianObat',
            fields=[
                ('tgl_perawatan', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('biaya_obat', models.FloatField(blank=True, null=True)),
                ('jml', models.FloatField()),
                ('embalase', models.FloatField(blank=True, null=True)),
                ('tuslah', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detail_pemberian_obat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPengajuanBarangMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pengajuan', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('jumlah2', models.FloatField()),
            ],
            options={
                'db_table': 'detail_pengajuan_barang_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPengeluaranObatBhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_batch', models.CharField(blank=True, max_length=20, null=True)),
                ('jumlah', models.FloatField()),
                ('harga_beli', models.FloatField()),
                ('total', models.FloatField()),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detail_pengeluaran_obat_bhp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPermintaanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'detail_permintaan_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPermintaanStokObatPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml', models.FloatField(blank=True, null=True)),
                ('aturan_pakai', models.CharField(blank=True, max_length=150, null=True)),
                ('pg', models.CharField(max_length=5)),
                ('sg', models.CharField(max_length=5)),
                ('sr', models.CharField(max_length=5)),
                ('ml', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'detail_permintaan_stok_obat_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailpesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pesan', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('jumlah2', models.FloatField(blank=True, null=True)),
                ('kadaluarsa', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detailpesan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailSuratPemesananMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pesan', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
                ('jumlah2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_surat_pemesanan_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detreturbeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_faktur', models.CharField(max_length=20)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jml_beli', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('jml_retur2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detreturbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detreturjual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_jual', models.CharField(max_length=20)),
                ('jml_jual', models.FloatField(blank=True, null=True)),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detreturjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GolonganBarang',
            fields=[
                ('kode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'golongan_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibahObatBhp',
            fields=[
                ('no_hibah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_hibah', models.DateField(blank=True, null=True)),
                ('totalhibah', models.FloatField()),
                ('totalnilai', models.FloatField()),
            ],
            options={
                'db_table': 'hibah_obat_bhp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('kdjns', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('kode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'kategori_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterAturanPakai',
            fields=[
                ('aturan', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'master_aturan_pakai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodeRacik',
            fields=[
                ('kd_racik', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nm_racik', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'metode_racik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObatbhpOk',
            fields=[
                ('kd_obat', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_obat', models.CharField(max_length=50)),
                ('hargasatuan', models.FloatField()),
            ],
            options={
                'db_table': 'obatbhp_ok',
                'managed': False,
            },
        ),
    ]
