# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
        ('farmasi', '0001_initial'),
        ('ralan', '0001_initial'),
        ('bangsal', '0001_initial'),
        ('asuransi', '0002_initial'),
        ('diagnosa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObatPenyakit',
            fields=[
                ('kd_penyakit', models.OneToOneField(db_column='kd_penyakit', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='diagnosa.penyakit')),
                ('referensi', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'obat_penyakit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObatRacikan',
            fields=[
                ('tgl_perawatan', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('no_racik', models.CharField(max_length=2)),
                ('nama_racik', models.CharField(max_length=100)),
                ('jml_dr', models.IntegerField()),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'obat_racikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PcareObatDiberikan',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('nokunjungan', models.CharField(db_column='noKunjungan', max_length=40)),
                ('kdobatsk', models.CharField(blank=True, db_column='kdObatSK', max_length=10, null=True)),
                ('tgl_perawatan', models.DateField()),
                ('jam', models.TimeField()),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pcare_obat_diberikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PembagianTuslah',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('persen', models.FloatField()),
            ],
            options={
                'db_table': 'pembagian_tuslah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_beli', models.DateField(blank=True, null=True)),
                ('total1', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total2', models.FloatField()),
                ('ppn', models.FloatField()),
                ('tagihan', models.FloatField()),
            ],
            options={
                'db_table': 'pembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_order', models.CharField(max_length=20)),
                ('tgl_pesan', models.DateField(blank=True, null=True)),
                ('tgl_faktur', models.DateField(blank=True, null=True)),
                ('tgl_tempo', models.DateField(blank=True, null=True)),
                ('total1', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total2', models.FloatField()),
                ('ppn', models.FloatField()),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanBarangMedis',
            fields=[
                ('no_pengajuan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pengajuan_barang_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengeluaranObatBhp',
            fields=[
                ('no_keluar', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pengeluaran_obat_bhp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('nota_jual', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_jual', models.DateField(blank=True, null=True)),
                ('nm_pasien', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=40, null=True)),
                ('jns_jual', models.CharField(blank=True, max_length=11, null=True)),
                ('ongkir', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'penjualan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanMedis',
            fields=[
                ('no_permintaan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'permintaan_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanObat',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
            ],
            options={
                'db_table': 'permintaan_obat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanStokObatPasien',
            fields=[
                ('no_permintaan', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('tgl_permintaan', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField()),
                ('status', models.CharField(max_length=5)),
                ('tgl_validasi', models.DateField()),
                ('jam_validasi', models.TimeField()),
            ],
            options={
                'db_table': 'permintaan_stok_obat_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml', models.FloatField(blank=True, null=True)),
                ('aturan_pakai', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'resep_dokter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepLuar',
            fields=[
                ('no_resep', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('tgl_perawatan', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField()),
                ('tgl_peresepan', models.DateField(blank=True, null=True)),
                ('jam_peresepan', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resep_luar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepObat',
            fields=[
                ('no_resep', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('tgl_perawatan', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField()),
                ('tgl_peresepan', models.DateField(blank=True, null=True)),
                ('jam_peresepan', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'resep_obat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepPulang',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('jml_barang', models.FloatField()),
                ('harga', models.FloatField()),
                ('total', models.FloatField()),
                ('dosis', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'resep_pulang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returbeli',
            fields=[
                ('no_retur_beli', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'returbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returjual',
            fields=[
                ('no_retur_jual', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'returjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returpasien',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('jml', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'returpasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatBarangMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_awal', models.FloatField(blank=True, null=True)),
                ('masuk', models.FloatField(blank=True, null=True)),
                ('keluar', models.FloatField(blank=True, null=True)),
                ('stok_akhir', models.FloatField()),
                ('posisi', models.CharField(blank=True, max_length=17, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'riwayat_barang_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetDepoRalan',
            fields=[
                ('kd_poli', models.OneToOneField(db_column='kd_poli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bangsal.poliklinik')),
            ],
            options={
                'db_table': 'set_depo_ralan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetDepoRanap',
            fields=[
                ('kd_bangsal', models.OneToOneField(db_column='kd_bangsal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='kd_bangsal_set_depo_ranap', serialize=False, to='bangsal.bangsal')),
            ],
            options={
                'db_table': 'set_depo_ranap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetEmbalase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embalase_per_obat', models.FloatField()),
                ('tuslah_per_obat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set_embalase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHargaObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setharga', models.CharField(max_length=10)),
                ('hargadasar', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'set_harga_obat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHargaObatRalan',
            fields=[
                ('kd_pj', models.OneToOneField(db_column='kd_pj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.penjab')),
                ('hargajual', models.FloatField()),
            ],
            options={
                'db_table': 'set_harga_obat_ralan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHargaObatRanap',
            fields=[
                ('kd_pj', models.OneToOneField(db_column='kd_pj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.penjab')),
                ('kelas', models.CharField(max_length=11)),
                ('hargajual', models.FloatField()),
            ],
            options={
                'db_table': 'set_harga_obat_ranap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetTuslah',
            fields=[
                ('tahun', models.TextField(primary_key=True, serialize=False)),
                ('bulan', models.IntegerField()),
                ('pendapatan_tuslah', models.FloatField()),
                ('persen_rs', models.FloatField()),
                ('bagian_rs', models.FloatField()),
                ('persen_kry', models.FloatField()),
                ('bagian_kry', models.FloatField()),
            ],
            options={
                'db_table': 'set_tuslah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StokObatPasien',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('jumlah', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('pg', models.CharField(max_length=5)),
                ('sg', models.CharField(max_length=5)),
                ('sr', models.CharField(max_length=5)),
                ('ml', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'stok_obat_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagihanObatLangsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besar_tagihan', models.FloatField()),
            ],
            options={
                'db_table': 'tagihan_obat_langsung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampjurnal',
            fields=[
                ('kd_rek', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_rek', models.CharField(blank=True, max_length=100, null=True)),
                ('debet', models.FloatField(blank=True, null=True)),
                ('kredit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tampjurnal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampjurnal2',
            fields=[
                ('kd_rek', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_rek', models.CharField(blank=True, max_length=100, null=True)),
                ('debet', models.FloatField(blank=True, null=True)),
                ('kredit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tampjurnal2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampreturbeli',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jml_beli', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('jml_retur2', models.FloatField(blank=True, null=True)),
                ('kadaluarsa', models.CharField(max_length=14)),
                ('petugas', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tampreturbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampreturjual',
            fields=[
                ('nota_jual', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(blank=True, max_length=100, null=True)),
                ('jml_jual', models.FloatField(blank=True, null=True)),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('petugas', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tampreturjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampreturpiutang',
            fields=[
                ('nota_piutang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(blank=True, max_length=100, null=True)),
                ('jml_piutang', models.FloatField(blank=True, null=True)),
                ('h_piutang', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tampreturpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitipFaktur',
            fields=[
                ('no_tagihan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuktiPemesanan',
            fields=[
                ('no_faktur', models.OneToOneField(db_column='no_faktur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.pemesanan')),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bukti_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailhibahObatBhp',
            fields=[
                ('no_hibah', models.OneToOneField(db_column='no_hibah', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.hibahobatbhp')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_hibah', models.FloatField(blank=True, null=True)),
                ('subtotalhibah', models.FloatField(blank=True, null=True)),
                ('h_diakui', models.FloatField()),
                ('subtotaldiakui', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('jumlah2', models.FloatField(blank=True, null=True)),
                ('kadaluarsa', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detailhibah_obat_bhp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailObatRacikanJual',
            fields=[
                ('nota_jual', models.OneToOneField(db_column='nota_jual', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.penjualan')),
                ('no_racik', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'detail_obat_racikan_jual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailTitipFaktur',
            fields=[
                ('no_tagihan', models.OneToOneField(db_column='no_tagihan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.titipfaktur')),
            ],
            options={
                'db_table': 'detail_titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gudangbarang',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('stok', models.FloatField()),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gudangbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingObatPcare',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('kode_brng_pcare', models.CharField(max_length=15)),
                ('nama_brng_pcare', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'maping_obat_pcare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mutasibarang',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('jml', models.FloatField()),
                ('harga', models.FloatField()),
                ('tanggal', models.DateTimeField()),
                ('keterangan', models.CharField(max_length=60)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mutasibarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObatRacikanJual',
            fields=[
                ('nota_jual', models.OneToOneField(db_column='nota_jual', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.penjualan')),
                ('no_racik', models.CharField(max_length=2)),
                ('nama_racik', models.CharField(max_length=100)),
                ('jml_dr', models.IntegerField()),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'obat_racikan_jual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opname',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('stok', models.FloatField()),
                ('real', models.FloatField()),
                ('selisih', models.FloatField()),
                ('nomihilang', models.FloatField()),
                ('lebih', models.FloatField()),
                ('nomilebih', models.FloatField()),
                ('keterangan', models.CharField(max_length=60)),
                ('no_batch', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'opname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepDokterRacikan',
            fields=[
                ('no_resep', models.OneToOneField(db_column='no_resep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.resepobat')),
                ('no_racik', models.CharField(max_length=2)),
                ('nama_racik', models.CharField(max_length=100)),
                ('jml_dr', models.IntegerField()),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'resep_dokter_racikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepDokterRacikanDetail',
            fields=[
                ('no_resep', models.OneToOneField(db_column='no_resep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.resepobat')),
                ('no_racik', models.CharField(max_length=2)),
                ('p1', models.FloatField(blank=True, null=True)),
                ('p2', models.FloatField(blank=True, null=True)),
                ('kandungan', models.CharField(blank=True, max_length=10, null=True)),
                ('jml', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resep_dokter_racikan_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepLuarObat',
            fields=[
                ('no_resep', models.OneToOneField(db_column='no_resep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.resepluar')),
                ('jml', models.FloatField(blank=True, null=True)),
                ('aturan_pakai', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'resep_luar_obat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepLuarRacikan',
            fields=[
                ('no_resep', models.OneToOneField(db_column='no_resep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.resepluar')),
                ('no_racik', models.CharField(max_length=2)),
                ('nama_racik', models.CharField(max_length=100)),
                ('jml_dr', models.IntegerField()),
                ('aturan_pakai', models.CharField(max_length=150)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'resep_luar_racikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResepLuarRacikanDetail',
            fields=[
                ('no_resep', models.OneToOneField(db_column='no_resep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.resepluar')),
                ('no_racik', models.CharField(max_length=2)),
                ('p1', models.FloatField(blank=True, null=True)),
                ('p2', models.FloatField(blank=True, null=True)),
                ('kandungan', models.CharField(blank=True, max_length=10, null=True)),
                ('jml', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resep_luar_racikan_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setpenjualanperbarang',
            fields=[
                ('ralan', models.FloatField(blank=True, null=True)),
                ('kelas1', models.FloatField(blank=True, null=True)),
                ('kelas2', models.FloatField(blank=True, null=True)),
                ('kelas3', models.FloatField(blank=True, null=True)),
                ('utama', models.FloatField(blank=True, null=True)),
                ('vip', models.FloatField(blank=True, null=True)),
                ('vvip', models.FloatField(blank=True, null=True)),
                ('beliluar', models.FloatField(blank=True, null=True)),
                ('jualbebas', models.FloatField(blank=True, null=True)),
                ('karyawan', models.FloatField(blank=True, null=True)),
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
            ],
            options={
                'db_table': 'setpenjualanperbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampbeli1',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('nama_brng', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('satuan_stok', models.CharField(blank=True, max_length=10, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('jumlah_stok', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tampbeli1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tampjual1',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('nama_brng', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField()),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tampjual1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tamppiutang',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='farmasi.databarang')),
                ('nama_brng', models.CharField(blank=True, max_length=80, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('no_batch', models.CharField(max_length=20)),
                ('petugas', models.CharField(max_length=20)),
                ('no_faktur', models.CharField(max_length=20)),
                ('aturan_pakai', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tamppiutang',
                'managed': False,
            },
        ),
    ]
