# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_uploud', models.DateField()),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'berkas_pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluasiKinerja',
            fields=[
                ('kode_evaluasi', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_evaluasi', models.CharField(blank=True, max_length=200, null=True)),
                ('indek', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluasi_kinerja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('kd_jbtn', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nm_jbtn', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JamJaga',
            fields=[
                ('no_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=13)),
                ('jam_masuk', models.TimeField()),
                ('jam_pulang', models.TimeField()),
            ],
            options={
                'db_table': 'jam_jaga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JamMasuk',
            fields=[
                ('shift', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('jam_masuk', models.TimeField()),
                ('jam_pulang', models.TimeField()),
            ],
            options={
                'db_table': 'jam_masuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jgmlm',
            fields=[
                ('tgl', models.DateField(primary_key=True, serialize=False)),
                ('jml', models.IntegerField()),
            ],
            options={
                'db_table': 'jgmlm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JnjJabatan',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('tnj', models.FloatField()),
                ('indek', models.IntegerField()),
            ],
            options={
                'db_table': 'jnj_jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KelompokJabatan',
            fields=[
                ('kode_kelompok', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_kelompok', models.CharField(blank=True, max_length=100, null=True)),
                ('indek', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kelompok_jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ketidakhadiran',
            fields=[
                ('tgl', models.DateField(primary_key=True, serialize=False)),
                ('jns', models.CharField(max_length=1)),
                ('ktg', models.CharField(max_length=40)),
                ('jml', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ketidakhadiran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Koperasi',
            fields=[
                ('stts', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('wajib', models.FloatField()),
            ],
            options={
                'db_table': 'koperasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterBerkasPegawai',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=31)),
                ('nama_berkas', models.CharField(max_length=300)),
                ('no_urut', models.IntegerField()),
            ],
            options={
                'db_table': 'master_berkas_pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('jk', models.CharField(max_length=6)),
                ('jbtn', models.CharField(max_length=25)),
                ('npwp', models.CharField(max_length=15)),
                ('gapok', models.FloatField()),
                ('tmp_lahir', models.CharField(max_length=20)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=60)),
                ('kota', models.CharField(max_length=20)),
                ('mulai_kerja', models.DateField()),
                ('ms_kerja', models.CharField(max_length=4)),
                ('rekening', models.CharField(max_length=25)),
                ('stts_aktif', models.CharField(max_length=11)),
                ('wajibmasuk', models.IntegerField()),
                ('pengurang', models.FloatField()),
                ('indek', models.IntegerField()),
                ('mulai_kontrak', models.DateField(blank=True, null=True)),
                ('cuti_diambil', models.IntegerField()),
                ('dankes', models.FloatField()),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('no_ktp', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PencapaianKinerja',
            fields=[
                ('kode_pencapaian', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_pencapaian', models.CharField(blank=True, max_length=200, null=True)),
                ('indek', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pencapaian_kinerja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('tingkat', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('indek', models.IntegerField()),
                ('gapok1', models.FloatField()),
                ('kenaikan', models.FloatField()),
                ('maksimal', models.IntegerField()),
            ],
            options={
                'db_table': 'pendidikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanCuti',
            fields=[
                ('no_pengajuan', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('urgensi', models.CharField(max_length=18)),
                ('alamat', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('kepentingan', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'pengajuan_cuti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Potongan',
            fields=[
                ('tahun', models.TextField(primary_key=True, serialize=False)),
                ('bulan', models.IntegerField()),
                ('bpjs', models.FloatField()),
                ('jamsostek', models.FloatField()),
                ('dansos', models.FloatField()),
                ('simwajib', models.FloatField()),
                ('angkop', models.FloatField()),
                ('angla', models.FloatField()),
                ('telpri', models.FloatField()),
                ('pajak', models.FloatField()),
                ('pribadi', models.FloatField()),
                ('lain', models.FloatField()),
                ('ktg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'potongan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('tgl', models.DateField(primary_key=True, serialize=False)),
                ('jns', models.CharField(max_length=2)),
                ('lembur', models.IntegerField()),
            ],
            options={
                'db_table': 'presensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResikoKerja',
            fields=[
                ('kode_resiko', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_resiko', models.CharField(blank=True, max_length=200, null=True)),
                ('indek', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resiko_kerja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetJgmlm',
            fields=[
                ('tnj', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'set_jgmlm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetKeterlambatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toleransi', models.IntegerField(blank=True, null=True)),
                ('terlambat1', models.IntegerField(blank=True, null=True)),
                ('terlambat2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set_keterlambatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetLemburhb',
            fields=[
                ('tnj', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'set_lemburhb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetLemburhr',
            fields=[
                ('tnj', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'set_lemburhr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spesialis',
            fields=[
                ('kd_sps', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nm_sps', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'spesialis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SttsKerja',
            fields=[
                ('stts', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ktg', models.CharField(max_length=20)),
                ('indek', models.IntegerField()),
            ],
            options={
                'db_table': 'stts_kerja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SttsWp',
            fields=[
                ('stts', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ktg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stts_wp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tambahjaga',
            fields=[
                ('tgl', models.DateField(primary_key=True, serialize=False)),
                ('jml', models.IntegerField()),
            ],
            options={
                'db_table': 'tambahjaga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AngsuranKoperasi',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_angsur', models.DateField()),
                ('pokok', models.FloatField()),
                ('jasa', models.FloatField()),
            ],
            options={
                'db_table': 'angsuran_koperasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('barcode', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'barcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('kd_dokter', models.OneToOneField(db_column='kd_dokter', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai', to_field='nik')),
                ('nm_dokter', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('gol_drh', models.CharField(blank=True, max_length=2, null=True)),
                ('agama', models.CharField(blank=True, max_length=12, null=True)),
                ('almt_tgl', models.CharField(blank=True, max_length=60, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('stts_nikah', models.CharField(blank=True, max_length=13, null=True)),
                ('alumni', models.CharField(blank=True, max_length=60, null=True)),
                ('no_ijn_praktek', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'dokter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluasiKinerjaPegawai',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tahun', models.TextField()),
                ('bulan', models.IntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'evaluasi_kinerja_pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JadwalPegawai',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tahun', models.TextField()),
                ('bulan', models.CharField(max_length=2)),
                ('h1', models.CharField(max_length=13)),
                ('h2', models.CharField(max_length=13)),
                ('h3', models.CharField(max_length=13)),
                ('h4', models.CharField(max_length=13)),
                ('h5', models.CharField(max_length=13)),
                ('h6', models.CharField(max_length=13)),
                ('h7', models.CharField(max_length=13)),
                ('h8', models.CharField(max_length=13)),
                ('h9', models.CharField(max_length=13)),
                ('h10', models.CharField(max_length=13)),
                ('h11', models.CharField(max_length=13)),
                ('h12', models.CharField(max_length=13)),
                ('h13', models.CharField(max_length=13)),
                ('h14', models.CharField(max_length=13)),
                ('h15', models.CharField(max_length=13)),
                ('h16', models.CharField(max_length=13)),
                ('h17', models.CharField(max_length=13)),
                ('h18', models.CharField(max_length=13)),
                ('h19', models.CharField(max_length=13)),
                ('h20', models.CharField(max_length=13)),
                ('h21', models.CharField(max_length=13)),
                ('h22', models.CharField(max_length=13)),
                ('h23', models.CharField(max_length=13)),
                ('h24', models.CharField(max_length=13)),
                ('h25', models.CharField(max_length=13)),
                ('h26', models.CharField(max_length=13)),
                ('h27', models.CharField(max_length=13)),
                ('h28', models.CharField(max_length=13)),
                ('h29', models.CharField(max_length=13)),
                ('h30', models.CharField(max_length=13)),
                ('h31', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'jadwal_pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JadwalTambahan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tahun', models.TextField()),
                ('bulan', models.CharField(max_length=2)),
                ('h1', models.CharField(max_length=13)),
                ('h2', models.CharField(max_length=13)),
                ('h3', models.CharField(max_length=13)),
                ('h4', models.CharField(max_length=13)),
                ('h5', models.CharField(max_length=13)),
                ('h6', models.CharField(max_length=13)),
                ('h7', models.CharField(max_length=13)),
                ('h8', models.CharField(max_length=13)),
                ('h9', models.CharField(max_length=13)),
                ('h10', models.CharField(max_length=13)),
                ('h11', models.CharField(max_length=13)),
                ('h12', models.CharField(max_length=13)),
                ('h13', models.CharField(max_length=13)),
                ('h14', models.CharField(max_length=13)),
                ('h15', models.CharField(max_length=13)),
                ('h16', models.CharField(max_length=13)),
                ('h17', models.CharField(max_length=13)),
                ('h18', models.CharField(max_length=13)),
                ('h19', models.CharField(max_length=13)),
                ('h20', models.CharField(max_length=13)),
                ('h21', models.CharField(max_length=13)),
                ('h22', models.CharField(max_length=13)),
                ('h23', models.CharField(max_length=13)),
                ('h24', models.CharField(max_length=13)),
                ('h25', models.CharField(max_length=13)),
                ('h26', models.CharField(max_length=13)),
                ('h27', models.CharField(max_length=13)),
                ('h28', models.CharField(max_length=13)),
                ('h29', models.CharField(max_length=13)),
                ('h30', models.CharField(max_length=13)),
                ('h31', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'jadwal_tambahan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keanggotaan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'keanggotaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PembagianAkte',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('persen', models.FloatField()),
            ],
            options={
                'db_table': 'pembagian_akte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PembagianResume',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('persen', models.FloatField()),
            ],
            options={
                'db_table': 'pembagian_resume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PembagianWarung',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('persen', models.FloatField()),
            ],
            options={
                'db_table': 'pembagian_warung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeminjamanKoperasi',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tanggal', models.DateField()),
                ('pinjaman', models.FloatField()),
                ('banyak_angsur', models.IntegerField()),
                ('pokok', models.FloatField()),
                ('jasa', models.FloatField()),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'peminjaman_koperasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PencapaianKinerjaPegawai',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tahun', models.TextField()),
                ('bulan', models.IntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pencapaian_kinerja_pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('nip', models.OneToOneField(db_column='nip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('gol_darah', models.CharField(blank=True, max_length=2, null=True)),
                ('agama', models.CharField(blank=True, max_length=12, null=True)),
                ('stts_nikah', models.CharField(blank=True, max_length=13, null=True)),
                ('alamat', models.CharField(blank=True, max_length=60, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'petugas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RekapPresensi',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('shift', models.CharField(max_length=13)),
                ('jam_datang', models.DateTimeField()),
                ('jam_pulang', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=25)),
                ('keterlambatan', models.CharField(max_length=20)),
                ('durasi', models.CharField(blank=True, max_length=20, null=True)),
                ('keterangan', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rekap_presensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatJabatan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('jabatan', models.CharField(max_length=50)),
                ('tmt_pangkat', models.DateField()),
                ('tmt_pangkat_yad', models.DateField()),
                ('pejabat_penetap', models.CharField(max_length=50)),
                ('nomor_sk', models.CharField(max_length=25)),
                ('tgl_sk', models.DateField()),
                ('dasar_peraturan', models.CharField(max_length=50)),
                ('masa_kerja', models.IntegerField()),
                ('bln_kerja', models.IntegerField()),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'riwayat_jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('pendidikan', models.CharField(max_length=11)),
                ('sekolah', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=40)),
                ('thn_lulus', models.TextField()),
                ('kepala', models.CharField(max_length=50)),
                ('pendanaan', models.CharField(max_length=28)),
                ('keterangan', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'riwayat_pendidikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPenelitian',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('jenis_penelitian', models.CharField(max_length=30)),
                ('peranan', models.CharField(max_length=30)),
                ('judul_penelitian', models.CharField(max_length=60)),
                ('judul_jurnal', models.CharField(max_length=60)),
                ('tahun', models.TextField()),
                ('biaya_penelitian', models.FloatField(blank=True, null=True)),
                ('asal_dana', models.CharField(max_length=30)),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'riwayat_penelitian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPenghargaan',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('jenis', models.CharField(max_length=30)),
                ('nama_penghargaan', models.CharField(max_length=60)),
                ('tanggal', models.DateField()),
                ('instansi', models.CharField(max_length=40)),
                ('pejabat_pemberi', models.CharField(max_length=40)),
                ('berkas', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'riwayat_penghargaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatSeminar',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('tingkat', models.CharField(max_length=13)),
                ('jenis', models.CharField(max_length=9)),
                ('nama_seminar', models.CharField(max_length=50)),
                ('peranan', models.CharField(max_length=40)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('penyelengara', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=50)),
                ('berkas', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'riwayat_seminar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetJgtambah',
            fields=[
                ('tnj', models.FloatField()),
                ('pendidikan', models.OneToOneField(db_column='pendidikan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pendidikan')),
            ],
            options={
                'db_table': 'set_jgtambah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sidikjari',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('sidikjari', models.TextField()),
            ],
            options={
                'db_table': 'sidikjari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryPresensi',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.pegawai')),
                ('shift', models.CharField(max_length=13)),
                ('jam_datang', models.DateTimeField(blank=True, null=True)),
                ('jam_pulang', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=25)),
                ('keterlambatan', models.CharField(max_length=20)),
                ('durasi', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'temporary_presensi',
                'managed': False,
            },
        ),
    ]
