# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ralan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsuhanGizi',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateField()),
                ('antropometri_bb', models.CharField(blank=True, max_length=5, null=True)),
                ('antropometri_tb', models.CharField(blank=True, max_length=5, null=True)),
                ('antropometri_imt', models.CharField(blank=True, max_length=5, null=True)),
                ('antropometri_lla', models.CharField(blank=True, max_length=5, null=True)),
                ('antropometri_tl', models.CharField(blank=True, max_length=5, null=True)),
                ('antropometri_ulna', models.CharField(max_length=5)),
                ('antropometri_bbideal', models.CharField(max_length=5)),
                ('antropometri_bbperu', models.CharField(max_length=5)),
                ('antropometri_tbperu', models.CharField(max_length=5)),
                ('antropometri_bbpertb', models.CharField(max_length=5)),
                ('antropometri_llaperu', models.CharField(max_length=5)),
                ('biokimia', models.CharField(blank=True, max_length=100, null=True)),
                ('fisik_klinis', models.CharField(blank=True, max_length=100, null=True)),
                ('alergi_telur', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_susu_sapi', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_kacang', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_gluten', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_udang', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_ikan', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi_hazelnut', models.CharField(blank=True, max_length=5, null=True)),
                ('pola_makan', models.CharField(blank=True, max_length=100, null=True)),
                ('riwayat_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('intervensi_gizi', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring_evaluasi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'asuhan_gizi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailBeriDiet',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'detail_beri_diet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('kd_diet', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_diet', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JamDietPasien',
            fields=[
                ('waktu', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('jam', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'jam_diet_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringAsuhanGizi',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateTimeField()),
                ('monitoring', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluasi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'monitoring_asuhan_gizi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkriningGizi',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal', models.DateTimeField()),
                ('skrining_bb', models.CharField(blank=True, max_length=5, null=True)),
                ('skrining_tb', models.CharField(blank=True, max_length=5, null=True)),
                ('alergi', models.CharField(blank=True, max_length=25, null=True)),
                ('parameter_imt', models.CharField(blank=True, max_length=30, null=True)),
                ('skor_imt', models.CharField(blank=True, max_length=5, null=True)),
                ('parameter_bb', models.CharField(blank=True, max_length=18, null=True)),
                ('skor_bb', models.CharField(blank=True, max_length=5, null=True)),
                ('parameter_penyakit', models.CharField(blank=True, max_length=33, null=True)),
                ('skor_penyakit', models.CharField(blank=True, max_length=5, null=True)),
                ('skor_total', models.CharField(blank=True, max_length=5, null=True)),
                ('parameter_total', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'skrining_gizi',
                'managed': False,
            },
        ),
    ]
