# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranap', '0001_initial'),
        ('pegawai', '0001_initial'),
        ('radiologi', '0001_initial'),
        ('laboratorium', '0001_initial'),
        ('asuransi', '0001_initial'),
        ('ralan', '0001_initial'),
        ('bangsal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhealthTindakanLaborat',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='laboratorium.jnsperawatanlab')),
                ('kd_inhealth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inhealth_tindakan_laborat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhealthTindakanOperasi',
            fields=[
                ('kode_paket', models.OneToOneField(db_column='kode_paket', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ranap.paketoperasi')),
                ('kd_inhealth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inhealth_tindakan_operasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhealthTindakanRadiologi',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='radiologi.jnsperawatanradiologi')),
                ('kd_inhealth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inhealth_tindakan_radiologi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhealthTindakanRalan',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.jnsperawatan')),
                ('kd_inhealth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inhealth_tindakan_ralan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhealthTindakanRanap',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ranap.jnsperawataninap')),
                ('kd_inhealth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inhealth_tindakan_ranap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jamsostek',
            fields=[
                ('stts', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('biaya', models.FloatField()),
            ],
            options={
                'db_table': 'jamsostek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingDokterDpjpvclaim',
            fields=[
                ('kd_dokter', models.OneToOneField(db_column='kd_dokter', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.dokter')),
                ('kd_dokter_bpjs', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_dokter_bpjs', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'maping_dokter_dpjpvclaim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingDokterPcare',
            fields=[
                ('kd_dokter', models.OneToOneField(db_column='kd_dokter', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pegawai.dokter')),
                ('kd_dokter_pcare', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_dokter_pcare', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'maping_dokter_pcare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingPoliBpjs',
            fields=[
                ('kd_poli_rs', models.OneToOneField(db_column='kd_poli_rs', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bangsal.poliklinik')),
                ('kd_poli_bpjs', models.CharField(max_length=15, unique=True)),
                ('nm_poli_bpjs', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'maping_poli_bpjs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingPoliklinikPcare',
            fields=[
                ('kd_poli_rs', models.OneToOneField(db_column='kd_poli_rs', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bangsal.poliklinik')),
                ('kd_poli_pcare', models.CharField(blank=True, max_length=5, null=True)),
                ('nm_poli_pcare', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'maping_poliklinik_pcare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingTindakanPcare',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.jnsperawatan')),
                ('kd_tindakan_pcare', models.CharField(blank=True, max_length=15, null=True)),
                ('nm_tindakan_pcare', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maping_tindakan_pcare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapingTindakanRanapPcare',
            fields=[
                ('kd_jenis_prw', models.OneToOneField(db_column='kd_jenis_prw', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ranap.jnsperawataninap')),
                ('kd_tindakan_pcare', models.CharField(blank=True, max_length=15, null=True)),
                ('nm_tindakan_pcare', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maping_tindakan_ranap_pcare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penjab',
            fields=[
                ('kd_pj', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('png_jawab', models.CharField(max_length=30)),
                ('nama_perusahaan', models.CharField(max_length=60)),
                ('alamat_asuransi', models.CharField(max_length=130)),
                ('no_telp', models.CharField(max_length=40)),
                ('attn', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'penjab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferensiMobilejknBpjs',
            fields=[
                ('nomorkartu', models.CharField(blank=True, max_length=25, null=True)),
                ('nik', models.CharField(blank=True, max_length=30, null=True)),
                ('nohp', models.CharField(blank=True, max_length=15, null=True)),
                ('kodepoli', models.CharField(blank=True, max_length=15, null=True)),
                ('pasienbaru', models.CharField(max_length=1)),
                ('norm', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggalperiksa', models.DateField(blank=True, null=True)),
                ('kodedokter', models.CharField(blank=True, max_length=20, null=True)),
                ('jampraktek', models.CharField(blank=True, max_length=12, null=True)),
                ('jeniskunjungan', models.CharField(blank=True, max_length=20, null=True)),
                ('nomorreferensi', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nomorantrean', models.CharField(max_length=15)),
                ('angkaantrean', models.CharField(max_length=5)),
                ('estimasidilayani', models.CharField(max_length=15)),
                ('sisakuotajkn', models.IntegerField()),
                ('kuotajkn', models.IntegerField()),
                ('sisakuotanonjkn', models.IntegerField()),
                ('kuotanonjkn', models.IntegerField()),
                ('status', models.CharField(max_length=7)),
                ('validasi', models.DateTimeField()),
                ('statuskirim', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'referensi_mobilejkn_bpjs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferensiMobilejknBpjsBatal',
            fields=[
                ('no_rawat_batal', models.CharField(blank=True, max_length=17, null=True)),
                ('nomorreferensi', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tanggalbatal', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('statuskirim', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'referensi_mobilejkn_bpjs_batal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RvpKlaimBpjs',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('tanggal_rvp', models.DateField(blank=True, null=True)),
                ('totalpiutang', models.FloatField(blank=True, null=True)),
                ('uangmuka', models.FloatField(blank=True, null=True)),
                ('sudahdibayar', models.FloatField(blank=True, null=True)),
                ('sisapiutang', models.FloatField(blank=True, null=True)),
                ('tarifinacbg', models.FloatField(blank=True, null=True)),
                ('dibayarbpjs', models.FloatField(blank=True, null=True)),
                ('persenbayar', models.FloatField(blank=True, null=True)),
                ('rugi', models.FloatField(blank=True, null=True)),
                ('lebih', models.FloatField(blank=True, null=True)),
                ('materialralan', models.FloatField(blank=True, null=True)),
                ('bhpralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakandrralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakanprralan', models.FloatField(blank=True, null=True)),
                ('ksoralan', models.FloatField(blank=True, null=True)),
                ('menejemenralan', models.FloatField(blank=True, null=True)),
                ('biaya_rawatralan', models.FloatField(blank=True, null=True)),
                ('materialranap', models.FloatField(blank=True, null=True)),
                ('bhpranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakandrranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakanprranap', models.FloatField(blank=True, null=True)),
                ('ksoranap', models.FloatField(blank=True, null=True)),
                ('menejemenranap', models.FloatField(blank=True, null=True)),
                ('biaya_rawatranap', models.FloatField(blank=True, null=True)),
                ('bagian_rslabralan', models.FloatField(blank=True, null=True)),
                ('bhplabralan', models.FloatField(blank=True, null=True)),
                ('tarif_perujuklabralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_dokterlabralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_petugaslabralan', models.FloatField(blank=True, null=True)),
                ('ksolabralan', models.FloatField(blank=True, null=True)),
                ('menejemenlabralan', models.FloatField(blank=True, null=True)),
                ('biayalabralan', models.FloatField(blank=True, null=True)),
                ('bagian_rslabranap', models.FloatField(blank=True, null=True)),
                ('bhplabranap', models.FloatField(blank=True, null=True)),
                ('tarif_perujuklabranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_dokterlabranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_petugaslabranap', models.FloatField(blank=True, null=True)),
                ('ksolabranap', models.FloatField(blank=True, null=True)),
                ('menejemenlabranap', models.FloatField(blank=True, null=True)),
                ('biayalabranap', models.FloatField(blank=True, null=True)),
                ('bagian_rsradiologiralan', models.FloatField(blank=True, null=True)),
                ('bhpradiologiralan', models.FloatField(blank=True, null=True)),
                ('tarif_perujukradiologiralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_dokterradiologiralan', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_petugasradiologiralan', models.FloatField(blank=True, null=True)),
                ('ksoradiologiralan', models.FloatField(blank=True, null=True)),
                ('menejemenradiologiralan', models.FloatField(blank=True, null=True)),
                ('biayaradiologiralan', models.FloatField(blank=True, null=True)),
                ('bagian_rsradiologiranap', models.FloatField(blank=True, null=True)),
                ('bhpradiologiranap', models.FloatField(blank=True, null=True)),
                ('tarif_perujukradiologiranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_dokterradiologiranap', models.FloatField(blank=True, null=True)),
                ('tarif_tindakan_petugasradiologiranap', models.FloatField(blank=True, null=True)),
                ('ksoradiologiranap', models.FloatField(blank=True, null=True)),
                ('menejemenradiologiranap', models.FloatField(blank=True, null=True)),
                ('biayaradiologiranap', models.FloatField(blank=True, null=True)),
                ('jmdokteroperasiralan', models.FloatField(blank=True, null=True)),
                ('jmparamedisoperasiralan', models.FloatField(blank=True, null=True)),
                ('bhpoperasiralan', models.FloatField(blank=True, null=True)),
                ('pendapatanoperasiralan', models.FloatField(blank=True, null=True)),
                ('jmdokteroperasiranap', models.FloatField(blank=True, null=True)),
                ('jmparamedisoperasiranap', models.FloatField(blank=True, null=True)),
                ('bhpoperasiranap', models.FloatField(blank=True, null=True)),
                ('pendapatanoperasiranap', models.FloatField(blank=True, null=True)),
                ('obatlangsung', models.FloatField(blank=True, null=True)),
                ('obatralan', models.FloatField(blank=True, null=True)),
                ('hppobatralan', models.FloatField(blank=True, null=True)),
                ('obatranap', models.FloatField(blank=True, null=True)),
                ('hppobatranap', models.FloatField(blank=True, null=True)),
                ('returobat', models.FloatField(blank=True, null=True)),
                ('tambahanbiaya', models.FloatField(blank=True, null=True)),
                ('potonganbiaya', models.FloatField(blank=True, null=True)),
                ('kamar', models.FloatField(blank=True, null=True)),
                ('reseppulang', models.FloatField(blank=True, null=True)),
                ('harianranap', models.FloatField(blank=True, null=True)),
                ('registrasi', models.FloatField(blank=True, null=True)),
                ('no_sep', models.CharField(max_length=40)),
                ('service', models.FloatField()),
            ],
            options={
                'db_table': 'rvp_klaim_bpjs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkdpBpjs',
            fields=[
                ('tahun', models.TextField(primary_key=True, serialize=False)),
                ('diagnosa', models.CharField(max_length=50)),
                ('terapi', models.CharField(max_length=50)),
                ('alasan1', models.CharField(blank=True, max_length=50, null=True)),
                ('alasan2', models.CharField(blank=True, max_length=50, null=True)),
                ('rtl1', models.CharField(blank=True, max_length=50, null=True)),
                ('rtl2', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('tanggal_rujukan', models.DateField()),
                ('no_antrian', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'skdp_bpjs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbahPenjab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_ubah', models.DateTimeField()),
            ],
            options={
                'db_table': 'ubah_penjab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BpjsPrb',
            fields=[
                ('no_sep', models.OneToOneField(db_column='no_sep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.bridgingsep')),
                ('prb', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bpjs_prb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BridgingRujukanBpjsKhusus',
            fields=[
                ('no_rujukan', models.OneToOneField(db_column='no_rujukan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.bridgingrujukanbpjs')),
                ('nokapst', models.CharField(blank=True, max_length=25, null=True)),
                ('nmpst', models.CharField(blank=True, max_length=100, null=True)),
                ('tglrujukan_awal', models.DateField(blank=True, null=True)),
                ('tglrujukan_berakhir', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bridging_rujukan_bpjs_khusus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BridgingRujukanBpjsKhususDiagnosa',
            fields=[
                ('no_rujukan', models.OneToOneField(db_column='no_rujukan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.bridgingrujukanbpjs')),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('kode_diagnosa', models.CharField(max_length=10)),
                ('nama_diagnosa', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'bridging_rujukan_bpjs_khusus_diagnosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BridgingRujukanBpjsKhususProsedur',
            fields=[
                ('no_rujukan', models.OneToOneField(db_column='no_rujukan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.bridgingrujukanbpjs')),
                ('kode_prosedur', models.CharField(max_length=10)),
                ('nama_prosedur', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'bridging_rujukan_bpjs_khusus_prosedur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BridgingSrbBpjs',
            fields=[
                ('no_sep', models.OneToOneField(db_column='no_sep', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.bridgingsep')),
                ('no_srb', models.CharField(max_length=10)),
                ('tgl_srb', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('kodeprogram', models.CharField(blank=True, max_length=3, null=True)),
                ('namaprogram', models.CharField(blank=True, max_length=70, null=True)),
                ('kodedpjp', models.CharField(blank=True, max_length=10, null=True)),
                ('nmdpjp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=25, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('saran', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bridging_srb_bpjs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordAsuransi',
            fields=[
                ('kd_pj', models.OneToOneField(db_column='kd_pj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.penjab')),
                ('usere', models.CharField(blank=True, max_length=700, null=True)),
                ('passworde', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'password_asuransi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferensiMobilejknBpjsTaskid',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asuransi.referensimobilejknbpjs')),
                ('taskid', models.CharField(max_length=1)),
                ('waktu', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referensi_mobilejkn_bpjs_taskid',
                'managed': False,
            },
        ),
    ]
