# Generated by Django 4.1 on 2022-11-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_bangsal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('singkatan', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorMutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250, verbose_name='Indikator Mutu')),
                ('target', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indikator_mutu',
            },
        ),
        migrations.CreateModel(
            name='DataIndikatorMutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_isi', models.DateField(blank=True, null=True)),
                ('numerator', models.IntegerField(blank=True, null=True)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('bangsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bangsal_indikatormutu', to='auth_bangsal.bangsal')),
                ('ind_mutu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator_mutu_data', to='auth_mutu.indikatormutu')),
            ],
            options={
                'db_table': 'data_indikator_mutu',
            },
        ),
    ]
