# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahasaPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahasa', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'bahasa_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacatFisik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cacat', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cacat_fisik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GolonganPolri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_golongan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'golongan_polri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GolonganTni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_golongan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'golongan_tni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JabatanPolri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'jabatan_polri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JabatanTni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'jabatan_tni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterImunisasi',
            fields=[
                ('kode_imunisasi', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_imunisasi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'master_imunisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PangkatPolri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pangkat', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pangkat_polri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PangkatTni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pangkat', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pangkat_tni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('no_rkm_medis', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_pasien', models.CharField(blank=True, max_length=40, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=20, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=15, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nm_ibu', models.CharField(max_length=40)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('gol_darah', models.CharField(blank=True, max_length=2, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=60, null=True)),
                ('stts_nikah', models.CharField(blank=True, max_length=13, null=True)),
                ('agama', models.CharField(blank=True, max_length=12, null=True)),
                ('tgl_daftar', models.DateField(blank=True, null=True)),
                ('no_tlp', models.CharField(blank=True, max_length=40, null=True)),
                ('umur', models.CharField(max_length=30)),
                ('pnd', models.CharField(max_length=14)),
                ('keluarga', models.CharField(blank=True, max_length=7, null=True)),
                ('namakeluarga', models.CharField(max_length=50)),
                ('no_peserta', models.CharField(blank=True, max_length=25, null=True)),
                ('pekerjaanpj', models.CharField(max_length=35)),
                ('alamatpj', models.CharField(max_length=100)),
                ('kelurahanpj', models.CharField(max_length=60)),
                ('kecamatanpj', models.CharField(max_length=60)),
                ('kabupatenpj', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=30)),
                ('propinsipj', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerusahaanPasien',
            fields=[
                ('kode_perusahaan', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama_perusahaan', models.CharField(blank=True, max_length=70, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('kota', models.CharField(blank=True, max_length=40, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=27, null=True)),
            ],
            options={
                'db_table': 'perusahaan_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SatuanPolri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satuan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'satuan_polri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SatuanTni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satuan', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'satuan_tni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetKelengkapanDataPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(blank=True, max_length=3, null=True)),
                ('p_no_ktp', models.IntegerField(blank=True, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=3, null=True)),
                ('p_tmp_lahir', models.IntegerField(blank=True, null=True)),
                ('nm_ibu', models.CharField(blank=True, max_length=3, null=True)),
                ('p_nm_ibu', models.IntegerField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=3, null=True)),
                ('p_alamat', models.IntegerField(blank=True, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=3, null=True)),
                ('p_pekerjaan', models.IntegerField(blank=True, null=True)),
                ('no_tlp', models.CharField(blank=True, max_length=3, null=True)),
                ('p_no_tlp', models.IntegerField(blank=True, null=True)),
                ('umur', models.CharField(blank=True, max_length=3, null=True)),
                ('p_umur', models.IntegerField(blank=True, null=True)),
                ('namakeluarga', models.CharField(blank=True, max_length=3, null=True)),
                ('p_namakeluarga', models.IntegerField(blank=True, null=True)),
                ('no_peserta', models.CharField(blank=True, max_length=3, null=True)),
                ('p_no_peserta', models.IntegerField(blank=True, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kelurahan', models.IntegerField(blank=True, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kecamatan', models.IntegerField(blank=True, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kabupaten', models.IntegerField(blank=True, null=True)),
                ('pekerjaanpj', models.CharField(blank=True, max_length=3, null=True)),
                ('p_pekerjaanpj', models.IntegerField(blank=True, null=True)),
                ('alamatpj', models.CharField(blank=True, max_length=3, null=True)),
                ('p_alamatpj', models.IntegerField(blank=True, null=True)),
                ('kelurahanpj', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kelurahanpj', models.IntegerField(blank=True, null=True)),
                ('kecamatanpj', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kecamatanpj', models.IntegerField(blank=True, null=True)),
                ('kabupatenpj', models.CharField(blank=True, max_length=3, null=True)),
                ('p_kabupatenpj', models.IntegerField(blank=True, null=True)),
                ('propinsi', models.CharField(max_length=3)),
                ('p_propinsi', models.IntegerField()),
                ('propinsipj', models.CharField(max_length=3)),
                ('p_propinsipj', models.IntegerField()),
            ],
            options={
                'db_table': 'set_kelengkapan_data_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SukuBangsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suku_bangsa', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'suku_bangsa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatatanPasien',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catatan_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasienBayi',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('umur_ibu', models.CharField(max_length=8)),
                ('nama_ayah', models.CharField(max_length=50)),
                ('umur_ayah', models.CharField(max_length=8)),
                ('berat_badan', models.CharField(max_length=10)),
                ('panjang_badan', models.CharField(max_length=10)),
                ('lingkar_kepala', models.CharField(max_length=10)),
                ('proses_lahir', models.CharField(max_length=60)),
                ('anakke', models.CharField(max_length=2)),
                ('jam_lahir', models.TimeField()),
                ('keterangan', models.CharField(max_length=50)),
                ('diagnosa', models.CharField(blank=True, max_length=60, null=True)),
                ('penyulit_kehamilan', models.CharField(blank=True, max_length=60, null=True)),
                ('ketuban', models.CharField(blank=True, max_length=60, null=True)),
                ('lingkar_perut', models.CharField(blank=True, max_length=10, null=True)),
                ('lingkar_dada', models.CharField(blank=True, max_length=10, null=True)),
                ('no_skl', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'pasien_bayi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasienCorona',
            fields=[
                ('no_pengenal', models.CharField(blank=True, max_length=20, null=True)),
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('inisial', models.CharField(blank=True, max_length=15, null=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=40, null=True)),
                ('tgl_masuk', models.DateField(blank=True, null=True)),
                ('kode_jk', models.CharField(blank=True, max_length=1, null=True)),
                ('nama_jk', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('kode_kewarganegaraan', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_kewarganegaraan', models.CharField(blank=True, max_length=25, null=True)),
                ('kode_penularan', models.CharField(blank=True, max_length=5, null=True)),
                ('sumber_penularan', models.CharField(blank=True, max_length=40, null=True)),
                ('kd_kelurahan', models.CharField(blank=True, max_length=15, null=True)),
                ('nm_kelurahan', models.CharField(blank=True, max_length=20, null=True)),
                ('kd_kecamatan', models.CharField(blank=True, max_length=10, null=True)),
                ('nm_kecamatan', models.CharField(blank=True, max_length=20, null=True)),
                ('kd_kabupaten', models.CharField(blank=True, max_length=6, null=True)),
                ('nm_kabupaten', models.CharField(blank=True, max_length=20, null=True)),
                ('kd_propinsi', models.CharField(blank=True, max_length=3, null=True)),
                ('nm_propinsi', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_keluar', models.DateField(blank=True, null=True)),
                ('kode_statuskeluar', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_statuskeluar', models.CharField(blank=True, max_length=40, null=True)),
                ('tgl_lapor', models.DateTimeField(blank=True, null=True)),
                ('kode_statusrawat', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_statusrawat', models.CharField(blank=True, max_length=40, null=True)),
                ('kode_statusisolasi', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_statusisolasi', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('notelp', models.CharField(blank=True, max_length=40, null=True)),
                ('sebab_kematian', models.CharField(blank=True, max_length=60, null=True)),
                ('kode_jenis_pasien', models.CharField(max_length=5)),
                ('nama_jenis_pasien', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'pasien_corona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasienMati',
            fields=[
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_meninggal', models.CharField(blank=True, max_length=24, null=True)),
                ('icd1', models.CharField(blank=True, max_length=20, null=True)),
                ('icd2', models.CharField(blank=True, max_length=20, null=True)),
                ('icd3', models.CharField(blank=True, max_length=20, null=True)),
                ('icd4', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pasien_mati',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasienPolri',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
            ],
            options={
                'db_table': 'pasien_polri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasienTni',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
            ],
            options={
                'db_table': 'pasien_tni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalPasien',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('gambar', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'personal_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatImunisasi',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('no_imunisasi', models.IntegerField()),
            ],
            options={
                'db_table': 'riwayat_imunisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPersalinanPasien',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('tgl_thn', models.CharField(max_length=12)),
                ('tempat_persalinan', models.CharField(blank=True, max_length=30, null=True)),
                ('usia_hamil', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_persalinan', models.CharField(blank=True, max_length=20, null=True)),
                ('penolong', models.CharField(blank=True, max_length=30, null=True)),
                ('penyulit', models.CharField(blank=True, max_length=40, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('bbpb', models.CharField(blank=True, max_length=10, null=True)),
                ('keadaan', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'riwayat_persalinan_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sidikjaripasien',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('sidikjari', models.TextField()),
            ],
            options={
                'db_table': 'sidikjaripasien',
                'managed': False,
            },
        ),
    ]
