# Generated by Django 4.1 on 2023-03-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasien',
            options={'managed': True},
        ),
    ]
