# Generated by Django 4.1 on 2023-03-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_alter_pasien_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasien',
            options={'managed': False},
        ),
    ]
