# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ralan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePasien',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('keluhan_utama', models.TextField()),
                ('jalannya_penyakit', models.TextField()),
                ('pemeriksaan_penunjang', models.TextField()),
                ('hasil_laborat', models.TextField()),
                ('diagnosa_utama', models.CharField(max_length=80)),
                ('kd_diagnosa_utama', models.CharField(max_length=10)),
                ('diagnosa_sekunder', models.CharField(max_length=80)),
                ('kd_diagnosa_sekunder', models.CharField(max_length=10)),
                ('diagnosa_sekunder2', models.CharField(max_length=80)),
                ('kd_diagnosa_sekunder2', models.CharField(max_length=10)),
                ('diagnosa_sekunder3', models.CharField(max_length=80)),
                ('kd_diagnosa_sekunder3', models.CharField(max_length=10)),
                ('diagnosa_sekunder4', models.CharField(max_length=80)),
                ('kd_diagnosa_sekunder4', models.CharField(max_length=10)),
                ('prosedur_utama', models.CharField(max_length=80)),
                ('kd_prosedur_utama', models.CharField(max_length=8)),
                ('prosedur_sekunder', models.CharField(max_length=80)),
                ('kd_prosedur_sekunder', models.CharField(max_length=8)),
                ('prosedur_sekunder2', models.CharField(max_length=80)),
                ('kd_prosedur_sekunder2', models.CharField(max_length=8)),
                ('prosedur_sekunder3', models.CharField(max_length=80)),
                ('kd_prosedur_sekunder3', models.CharField(max_length=8)),
                ('kondisi_pulang', models.CharField(max_length=9)),
                ('obat_pulang', models.TextField()),
            ],
            options={
                'db_table': 'resume_pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rujuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rujuk', models.CharField(max_length=40)),
                ('rujuk_ke', models.CharField(blank=True, max_length=150, null=True)),
                ('tgl_rujuk', models.DateField(blank=True, null=True)),
                ('keterangan_diagnosa', models.TextField(blank=True, null=True)),
                ('kat_rujuk', models.CharField(blank=True, max_length=9, null=True)),
                ('ambulance', models.CharField(blank=True, max_length=7, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rujuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RujukanInternalPoli',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
            ],
            options={
                'db_table': 'rujukan_internal_poli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RujukanranapDokterRs',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('jasarujuk', models.FloatField()),
            ],
            options={
                'db_table': 'rujukanranap_dokter_rs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RujukMasuk',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('perujuk', models.CharField(blank=True, max_length=60, null=True)),
                ('alamat', models.CharField(max_length=70)),
                ('no_rujuk', models.CharField(max_length=40)),
                ('jm_perujuk', models.FloatField()),
                ('dokter_perujuk', models.CharField(blank=True, max_length=50, null=True)),
                ('kategori_rujuk', models.CharField(blank=True, max_length=9, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('no_balasan', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'rujuk_masuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SisruteRujukanKeluar',
            fields=[
                ('no_rawat', models.OneToOneField(db_column='no_rawat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ralan.regperiksa')),
                ('no_rujuk', models.CharField(max_length=40)),
                ('no_rkm_medis', models.CharField(max_length=15)),
                ('nm_pasien', models.CharField(max_length=40)),
                ('no_ktp', models.CharField(max_length=20)),
                ('no_peserta', models.CharField(max_length=25)),
                ('jk', models.CharField(max_length=1)),
                ('tgl_lahir', models.DateField()),
                ('tmp_lahir', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=200)),
                ('no_tlp', models.CharField(max_length=40)),
                ('jns_rujukan', models.CharField(max_length=21)),
                ('tgl_rujuk', models.DateTimeField()),
                ('kd_faskes_tujuan', models.CharField(max_length=12)),
                ('nm_faskes_tujuan', models.CharField(max_length=200)),
                ('kd_alasan', models.CharField(max_length=5)),
                ('alasan_rujuk', models.CharField(max_length=150)),
                ('alasan_lainnya', models.CharField(max_length=50)),
                ('kd_diagnosa', models.CharField(max_length=10)),
                ('diagnosa_rujuk', models.TextField()),
                ('nik_dokter', models.CharField(max_length=20)),
                ('dokter_perujuk', models.CharField(max_length=50)),
                ('nik_petugas', models.CharField(max_length=20)),
                ('petugas_entry', models.CharField(max_length=50)),
                ('anamnesis_pemeriksaan', models.TextField()),
                ('kesadaran', models.CharField(max_length=14)),
                ('tekanan_darah', models.CharField(max_length=7)),
                ('nadi', models.CharField(max_length=3)),
                ('suhu', models.CharField(max_length=5)),
                ('respirasi', models.CharField(max_length=3)),
                ('keadaan_umum', models.TextField()),
                ('tingkat_nyeri', models.CharField(max_length=14)),
                ('alergi', models.CharField(max_length=50)),
                ('laboratorium', models.TextField()),
                ('radiologi', models.TextField()),
                ('terapitindakan', models.TextField()),
            ],
            options={
                'db_table': 'sisrute_rujukan_keluar',
                'managed': False,
            },
        ),
    ]
