# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeriBhpRadiologi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_periksa', models.DateField()),
                ('jam', models.TimeField()),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beri_bhp_radiologi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPengajuanBarangNonmedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pengajuan', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'detail_pengajuan_barang_nonmedis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPermintaanNonMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'detail_permintaan_non_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailSuratPemesananNonMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pesan', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'detail_surat_pemesanan_non_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('no_inventaris', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('asal_barang', models.CharField(blank=True, max_length=7, null=True)),
                ('tgl_pengadaan', models.DateField(blank=True, null=True)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('status_barang', models.CharField(blank=True, max_length=9, null=True)),
                ('no_rak', models.CharField(blank=True, max_length=3, null=True)),
                ('no_box', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'inventaris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisBarang',
            fields=[
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(blank=True, max_length=60, null=True)),
                ('jml_barang', models.IntegerField(blank=True, null=True)),
                ('thn_produksi', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inventaris_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisDetailPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'inventaris_detail_pesan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisHibah',
            fields=[
                ('no_hibah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_hibah', models.DateField(blank=True, null=True)),
                ('totalhibah', models.FloatField()),
            ],
            options={
                'db_table': 'inventaris_hibah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisJenis',
            fields=[
                ('id_jenis', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'inventaris_jenis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisKategori',
            fields=[
                ('id_kategori', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'inventaris_kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisMerk',
            fields=[
                ('id_merk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_merk', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'inventaris_merk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisPembelian',
            fields=[
                ('no_faktur', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_beli', models.DateField()),
                ('subtotal', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total', models.FloatField()),
                ('ppn', models.FloatField(blank=True, null=True)),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventaris_pembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisPemesanan',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_order', models.CharField(max_length=20)),
                ('tgl_pesan', models.DateField(blank=True, null=True)),
                ('tgl_faktur', models.DateField(blank=True, null=True)),
                ('tgl_tempo', models.DateField(blank=True, null=True)),
                ('total1', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total2', models.FloatField()),
                ('ppn', models.FloatField()),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
                ('kd_rek_aset', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inventaris_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisPeminjaman',
            fields=[
                ('peminjam', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tlp', models.CharField(max_length=13)),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('status_pinjam', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'inventaris_peminjaman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisRuang',
            fields=[
                ('id_ruang', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_ruang', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'inventaris_ruang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisTitipFaktur',
            fields=[
                ('no_tagihan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'inventaris_titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsbarang',
            fields=[
                ('kode_brng', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(max_length=80)),
                ('stok', models.FloatField()),
                ('harga', models.FloatField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ipsrsbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsdetailbeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'ipsrsdetailbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsdetailpengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'ipsrsdetailpengeluaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsdetailpesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'ipsrsdetailpesan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsDetailReturbeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_faktur', models.CharField(max_length=20)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipsrs_detail_returbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsHibah',
            fields=[
                ('no_hibah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_hibah', models.DateField(blank=True, null=True)),
                ('totalhibah', models.FloatField()),
                ('keterangan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ipsrs_hibah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsjenisbarang',
            fields=[
                ('kd_jenis', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nm_jenis', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ipsrsjenisbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrspembelian',
            fields=[
                ('no_faktur', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_beli', models.DateField()),
                ('subtotal', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total', models.FloatField()),
                ('ppn', models.FloatField(blank=True, null=True)),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipsrspembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrspemesanan',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_order', models.CharField(max_length=20)),
                ('tgl_pesan', models.DateField(blank=True, null=True)),
                ('tgl_faktur', models.DateField(blank=True, null=True)),
                ('tgl_tempo', models.DateField(blank=True, null=True)),
                ('total1', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total2', models.FloatField()),
                ('ppn', models.FloatField()),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'ipsrspemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrspengeluaran',
            fields=[
                ('no_keluar', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ipsrspengeluaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsreturbeli',
            fields=[
                ('no_retur_beli', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=40)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'ipsrsreturbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsRiwayatBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_awal', models.FloatField(blank=True, null=True)),
                ('masuk', models.FloatField(blank=True, null=True)),
                ('keluar', models.FloatField(blank=True, null=True)),
                ('stok_akhir', models.FloatField()),
                ('posisi', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'ipsrs_riwayat_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsTitipFaktur',
            fields=[
                ('no_tagihan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ipsrs_titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeminjamanBerkas',
            fields=[
                ('peminjam', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('status_pinjam', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'peminjaman_berkas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanBarangNonmedis',
            fields=[
                ('no_pengajuan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pengajuan_barang_nonmedis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanInventaris',
            fields=[
                ('no_pengajuan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('urgensi', models.CharField(max_length=9)),
                ('latar_belakang', models.CharField(max_length=200)),
                ('nama_barang', models.CharField(max_length=70)),
                ('spesifikasi', models.CharField(max_length=200)),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('total', models.FloatField()),
                ('keterangan', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'pengajuan_inventaris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanNonMedis',
            fields=[
                ('no_permintaan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ruang', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'permintaan_non_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermintaanPerbaikanInventaris',
            fields=[
                ('no_permintaan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('deskripsi_kerusakan', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'permintaan_perbaikan_inventaris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AkunAsetInventaris',
            fields=[
                ('id_jenis', models.OneToOneField(db_column='id_jenis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventarisjenis')),
            ],
            options={
                'db_table': 'akun_aset_inventaris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuktiPemesananLogistik',
            fields=[
                ('no_faktur', models.OneToOneField(db_column='no_faktur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.ipsrspemesanan')),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bukti_pemesanan_logistik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CssdBarang',
            fields=[
                ('no_inventaris', models.OneToOneField(db_column='no_inventaris', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventaris')),
                ('jenis_barang', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'cssd_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisBuktiPemesanan',
            fields=[
                ('no_faktur', models.OneToOneField(db_column='no_faktur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventarispemesanan')),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'inventaris_bukti_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisDetailBeli',
            fields=[
                ('no_faktur', models.OneToOneField(db_column='no_faktur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventarispembelian')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'inventaris_detail_beli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisDetailHibah',
            fields=[
                ('no_hibah', models.OneToOneField(db_column='no_hibah', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='no_hibah_inventaris_detail_hibah', serialize=False, to='aset.inventarishibah')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_hibah', models.FloatField(blank=True, null=True)),
                ('subtotalhibah', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventaris_detail_hibah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarisDetailTitipFaktur',
            fields=[
                ('no_tagihan', models.OneToOneField(db_column='no_tagihan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventaristitipfaktur')),
            ],
            options={
                'db_table': 'inventaris_detail_titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsDetailHibah',
            fields=[
                ('no_hibah', models.OneToOneField(db_column='no_hibah', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.ipsrshibah')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_hibah', models.FloatField(blank=True, null=True)),
                ('subtotalhibah', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipsrs_detail_hibah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsrsDetailTitipFaktur',
            fields=[
                ('no_tagihan', models.OneToOneField(db_column='no_tagihan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.ipsrstitipfaktur')),
            ],
            options={
                'db_table': 'ipsrs_detail_titip_faktur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipsrsopname',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.ipsrsbarang')),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('stok', models.IntegerField()),
                ('real', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('nomihilang', models.FloatField()),
                ('lebih', models.IntegerField()),
                ('nomilebih', models.FloatField()),
                ('keterangan', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'ipsrsopname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PemeliharaanInventaris',
            fields=[
                ('no_inventaris', models.OneToOneField(db_column='no_inventaris', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.inventaris')),
                ('tanggal', models.DateField()),
                ('uraian_kegiatan', models.CharField(max_length=255)),
                ('pelaksana', models.CharField(max_length=19)),
                ('biaya', models.FloatField()),
                ('jenis_pemeliharaan', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'pemeliharaan_inventaris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerbaikanInventaris',
            fields=[
                ('no_permintaan', models.OneToOneField(db_column='no_permintaan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aset.permintaanperbaikaninventaris')),
                ('tanggal', models.DateField()),
                ('uraian_kegiatan', models.CharField(max_length=255)),
                ('pelaksana', models.CharField(max_length=19)),
                ('biaya', models.FloatField()),
                ('keterangan', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'perbaikan_inventaris',
                'managed': False,
            },
        ),
    ]
