# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('pasien', '0003_alter_pasien_options'),
    # ]

    operations = [
        migrations.CreateModel(
            name='DiagnosaCorona',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasiencorona')),
                ('kode_icd', models.CharField(max_length=10)),
                ('nama_penyakit', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'diagnosa_corona',
                'managed': False,
            },
        ),
    ]
