# Generated by Django 4.1 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokobarang',
            fields=[
                ('kode_brng', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nama_brng', models.CharField(max_length=80)),
                ('stok', models.FloatField()),
                ('dasar', models.FloatField()),
                ('h_beli', models.FloatField()),
                ('distributor', models.FloatField()),
                ('grosir', models.FloatField()),
                ('retail', models.FloatField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tokobarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoBayarPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_bayar', models.DateField(blank=True, null=True)),
                ('besar_bayar', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_bukti', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'toko_bayar_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoBayarPiutang',
            fields=[
                ('tgl_bayar', models.DateField(primary_key=True, serialize=False)),
                ('besar_cicilan', models.FloatField()),
                ('catatan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'toko_bayar_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailBeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'toko_detail_beli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailJual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('tambahan', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toko_detail_jual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailPengajuanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pengajuan', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'toko_detail_pengajuan_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('harga', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'toko_detail_pesan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('bsr_dis', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toko_detail_piutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailReturbeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_faktur', models.CharField(max_length=20)),
                ('h_beli', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toko_detail_returbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailReturjual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_jual', models.CharField(max_length=15)),
                ('h_jual', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toko_detail_returjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDetailReturpiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_piutang', models.CharField(max_length=15)),
                ('h_piutang', models.FloatField(blank=True, null=True)),
                ('h_retur', models.FloatField(blank=True, null=True)),
                ('jml_retur', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toko_detail_returpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoDInteetailSuratPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(blank=True, null=True)),
                ('h_pesan', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('dis', models.FloatField()),
                ('besardis', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'toko_detail_surat_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokojenisbarang',
            fields=[
                ('kd_jenis', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nm_jenis', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tokojenisbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokomember',
            fields=[
                ('no_member', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=60, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'tokomember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokopembelian',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tgl_beli', models.DateField()),
                ('subtotal', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total', models.FloatField()),
                ('ppn', models.FloatField(blank=True, null=True)),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tokopembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokopemesanan',
            fields=[
                ('no_faktur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_order', models.CharField(max_length=20)),
                ('tgl_pesan', models.DateField(blank=True, null=True)),
                ('tgl_faktur', models.DateField(blank=True, null=True)),
                ('tgl_tempo', models.DateField(blank=True, null=True)),
                ('total1', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total2', models.FloatField()),
                ('ppn', models.FloatField()),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'tokopemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoPengajuanBarang',
            fields=[
                ('no_pengajuan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'toko_pengajuan_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokopenjualan',
            fields=[
                ('nota_jual', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_jual', models.DateField(blank=True, null=True)),
                ('nm_member', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=40, null=True)),
                ('jns_jual', models.CharField(blank=True, max_length=11, null=True)),
                ('ongkir', models.FloatField(blank=True, null=True)),
                ('ppn', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'tokopenjualan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokopiutang',
            fields=[
                ('nota_piutang', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_piutang', models.DateField(blank=True, null=True)),
                ('nm_member', models.CharField(blank=True, max_length=50, null=True)),
                ('catatan', models.CharField(blank=True, max_length=40, null=True)),
                ('jns_jual', models.CharField(blank=True, max_length=11, null=True)),
                ('ongkir', models.FloatField(blank=True, null=True)),
                ('uangmuka', models.FloatField(blank=True, null=True)),
                ('sisapiutang', models.FloatField()),
                ('tgltempo', models.DateField()),
            ],
            options={
                'db_table': 'tokopiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokoreturbeli',
            fields=[
                ('no_retur_beli', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=40)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'tokoreturbeli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokoreturjual',
            fields=[
                ('no_retur_jual', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=40)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'tokoreturjual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokoreturpiutang',
            fields=[
                ('no_retur_piutang', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tgl_retur', models.DateField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=40)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'tokoreturpiutang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoRiwayatBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_awal', models.FloatField(blank=True, null=True)),
                ('masuk', models.FloatField(blank=True, null=True)),
                ('keluar', models.FloatField(blank=True, null=True)),
                ('stok_akhir', models.FloatField()),
                ('posisi', models.CharField(blank=True, max_length=13, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'toko_riwayat_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokosetharga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.FloatField()),
                ('grosir', models.FloatField()),
                ('retail', models.FloatField()),
            ],
            options={
                'db_table': 'tokosetharga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokosuplier',
            fields=[
                ('kode_suplier', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_suplier', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('rekening', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tokosuplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokoSuratPemesanan',
            fields=[
                ('no_pemesanan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('subtotal', models.FloatField()),
                ('potongan', models.FloatField()),
                ('total', models.FloatField()),
                ('ppn', models.FloatField(blank=True, null=True)),
                ('meterai', models.FloatField(blank=True, null=True)),
                ('tagihan', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'toko_surat_pemesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokoopname',
            fields=[
                ('kode_brng', models.OneToOneField(db_column='kode_brng', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='toko.tokobarang')),
                ('dasar', models.FloatField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('stok', models.IntegerField()),
                ('real', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('nomihilang', models.FloatField()),
                ('keterangan', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tokoopname',
                'managed': False,
            },
        ),
    ]
