# Generated by Django 4.0.6 on 2022-08-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgingDukcapil',
            fields=[
                ('no_rkm_medis', models.OneToOneField(db_column='no_rkm_medis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasien.pasien')),
                ('no_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'bridging_dukcapil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('kd_kab', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kab', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'kabupaten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('kd_kec', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kec', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'kecamatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('kd_kel', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kel', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'kelurahan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogDukcapil',
            fields=[
                ('no_ktp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField()),
                ('user', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'log_dukcapil_aceh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propinsi',
            fields=[
                ('kd_prop', models.AutoField(primary_key=True, serialize=False)),
                ('nm_prop', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'propinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetAlamatPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelurahan', models.CharField(blank=True, max_length=5, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=5, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=5, null=True)),
                ('propinsi', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'set_alamat_pasien',
                'managed': False,
            },
        ),
    ]
