# Generated by Django 4.1 on 2023-03-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alamat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabupaten',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kelurahan',
            options={'managed': True},
        ),
    ]
