# Generated by Django 4.1 on 2023-03-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alamat', '0002_alter_kabupaten_options_alter_kecamatan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabupaten',
            name='kd_prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alamat.propinsi'),
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kd_kab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alamat.kabupaten'),
        ),
        migrations.AddField(
            model_name='kelurahan',
            name='kd_kec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alamat.kecamatan'),
        ),
    ]
