# Generated by Django 4.1 on 2023-05-04 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_user', models.BooleanField(default=False, verbose_name='officer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_pasien', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=50, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=20)),
                ('no_rkm_medis', models.CharField(blank=True, max_length=6)),
                ('no_reg', models.CharField(blank=True, max_length=8)),
                ('no_rawat', models.CharField(blank=True, max_length=17)),
                ('jk', models.CharField(blank=True, max_length=1, null=True)),
                ('tmp_lahir', models.CharField(blank=True, max_length=15, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nm_ibu', models.CharField(blank=True, max_length=40)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('gol_darah', models.CharField(blank=True, max_length=2, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=60, null=True)),
                ('stts_nikah', models.CharField(blank=True, max_length=13, null=True)),
                ('agama', models.CharField(blank=True, max_length=12, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
