# Generated by Django 4.1 on 2023-05-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0001_initial'),
        ('auth_bangsal', '0002_alter_bangsal_options_alter_bidang_options_and_more'),
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalasi_user', to='auth_bangsal.bangsal'),
        ),
        migrations.AddField(
            model_name='profiluser',
            name='pokja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.pokjaakreditasi'),
        ),
    ]
