# Generated by Django 4.1 on 2022-11-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokjaAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandarAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.pokjaakreditasi')),
            ],
        ),
        migrations.AddField(
            model_name='pokjaakreditasi',
            name='rumah_sakit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.rumahsakit'),
        ),
        migrations.CreateModel(
            name='KategoriElementPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=10)),
                ('metode', models.CharField(blank=True, max_length=50)),
                ('skor', models.IntegerField(default=0)),
                ('jlh_kat_skor', models.CharField(default='3', max_length=1)),
                ('skor_max', models.IntegerField(default=10)),
                ('sasaran', models.CharField(blank=True, max_length=200)),
                ('tahun', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.elementpenilaian')),
            ],
        ),
        migrations.CreateModel(
            name='FileAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='akreditasi/')),
                ('status', models.CharField(choices=[('Belum Dikerjakan', 'Belum Dikerjakan'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Belum Dikerjakan', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.kategorielementpenilaian')),
            ],
        ),
        migrations.AddField(
            model_name='elementpenilaian',
            name='standar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.standarakreditasi'),
        ),
    ]
